<a href="https://colab.research.google.com/github/vasavibantupalli-web/DataAnalysis_Codegnan2026/blob/main/data_analytics.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
num = int(input('enter a number= '))
if num>0:
 print("positive")
if num<0:
 print("negative")

enter a number= 5
positive

In [ ]:
import pandas as pd
print("pandas imported")

pandas imported

In [ ]:
#creating series
data = [1,2,3,4]
s = pd.Series(data)
print(s)

0    1
1    2
2    3
3    4
dtype: int64

In [ ]:
data = [1,2,3,4,5]
i= ['a','b','e','c','d']
s = pd.Series(data,index =i)
print(s)
#updating
s['a']=10
print(s)
s['c']=30
print(s)
#inserting new data(directly,concat)
s['f']=80
print(s)
#remove(drop method)
s = s.drop('a')
print(s)

a    1
b    2
e    3
c    4
d    5
dtype: int64
a    10
b     2
e     3
c     4
d     5
dtype: int64
a    10
b     2
e     3
c    30
d     5
dtype: int64
a    10
b     2
e     3
c    30
d     5
f    80
dtype: int64
b     2
e     3
c    30
d     5
f    80
dtype: int64

In [ ]:
#creating a series from adictionary
s2 = pd.Series({'x':100, 'y':200, 'z':300})
print(s2)

x    100
y    200
z    300
dtype: int64

In [ ]:
#accessing elements
print(s2[0])
print(s2[0:2])
print(s2[1:])
print(s2[:2])

100
x    100
y    200
dtype: int64
y    200
z    300
dtype: int64
x    100
y    200
dtype: int64

/tmp/ipykernel_2306/3002422712.py:2: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  print(s2[0])

In [ ]:
print(s2[0])
print(s2[0:2])
print(s2[1:])
print(s2[:2])
print(s2[2])

100
x    100
y    200
dtype: int64
y    200
z    300
dtype: int64
x    100
y    200
dtype: int64
300

/tmp/ipykernel_2306/1436243.py:1: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  print(s2[0])
/tmp/ipykernel_2306/1436243.py:5: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  print(s2[2])

In [ ]:
import pandas as pd
data = [78,85,92,67,88]
roll=[101,102,103,104,105]
s =pd.Series(data,index=roll)
print(s)
print(s[103])
s[104]=75
print(s)
s = s.drop(102)
print(s)
s[106] =90
print(s)

101    78
102    85
103    92
104    67
105    88
dtype: int64
92
101    78
102    85
103    92
104    75
105    88
dtype: int64
101    78
103    92
104    75
105    88
dtype: int64
101    78
103    92
104    75
105    88
106    90
dtype: int64

In [ ]:
import pandas as pd
product = ['p101','p102','p103','p104','p105']
price = [500,750,1200,900,1500]
s = pd.Series(product,index=price)
print(s)
s=s.drop[p102]
s[p102] = 800
print(s)
s = s.drop(p104)
print(s)

500     p101
750     p102
1200    p103
900     p104
1500    p105
dtype: object

NameError: name 'p102' is not defined

In [ ]:
s = pd.Series(
    [5000,7000,6000,9000,8000],


    index=["monday","tuesday","wednusday","thursday","friday"]

)

print(s)
print()
s.head(2)
s.head(3)
print(s.tail)
print(s)
len(s)

monday       5000
tuesday      7000
wednusday    6000
thursday     9000
friday       8000
dtype: int64

<bound method NDFrame.tail of monday       5000
tuesday      7000
wednusday    6000
thursday     9000
friday       8000
dtype: int64>
monday       5000
tuesday      7000
wednusday    6000
thursday     9000
friday       8000
dtype: int64

5

In [ ]:
s = pd.Series(
    [5000,7000,6000,9000,8000],


    index=["monday","tuesday","wednusday","thursday","friday"]

)

print(s)
print()
s.head(2)
s.head(3)

In [ ]:
s = pd.Series(
    [5000,7000,6000,9000,8000],


    index=["monday","tuesday","wednusday","thursday","friday"]

)

print(s)
print(5000)
print(s.index)
print(s.shape)
print(s.values)

NameError: name 'pd' is not defined

In [ ]:
#selecting multiple values
s = pd.Series(
    [5000,7000,6000,9000,8000],


    index=["monday","tuesday","wednusday","thursday","friday"]

)
print(s[["monday","wednusday"]])

monday       5000
wednusday    6000
dtype: int64

In [ ]:
#selecting/filtering
s = pd.Series(
    [5000,7000,6000,9000,8000],


    index=["monday","tuesday","wednusday","thursday","friday"]

)

print(s["monday"])

5000

In [ ]:
#filtering using a a condition
s = pd.Series(
    [5000,7000,6000,9000,8000],


    index=["monday","tuesday","wednusday","thursday","friday"]

)
print(s>6000)
print(s[s>6000])

monday       False
tuesday       True
wednusday    False
thursday      True
friday        True
dtype: bool
tuesday     7000
thursday    9000
friday      8000
dtype: int64

In [ ]:
#cleaning data
import pandas as pd
s = pd.Series([5000,7000,None,9000,None])
print(s)

0    5000.0
1    7000.0
2       NaN
3    9000.0
4       NaN
dtype: float64

In [ ]:
#isna
s = pd.Series([5000,7000,None,9000,None])

print(s)

0    5000.0
1    7000.0
2       NaN
3    9000.0
4       NaN
dtype: float64

In [ ]:
#count missing values
import pandas as pd
s = pd.Series([5000,7000,None,9000,None])
print(s)

print(s.isna().sum)
print(s.isna())

0    5000.0
1    7000.0
2       NaN
3    9000.0
4       NaN
dtype: float64
<bound method Series.sum of 0    False
1    False
2     True
3    False
4     True
dtype: bool>
0    False
1    False
2     True
3    False
4     True
dtype: bool

In [ ]:
#fillna()
import pandas as pd
s = pd.Series([5000,7000,None,9000,None])
print(s)

print(s.fillna(0))

0    5000.0
1    7000.0
2       NaN
3    9000.0
4       NaN
dtype: float64
0    5000.0
1    7000.0
2       0.0
3    9000.0
4       0.0
dtype: float64

In [ ]:
#drop na
s = pd.Series([5000,7000,None,9000,None])
print(s)

print(s.dropna())

0    5000.0
1    7000.0
2       NaN
3    9000.0
4       NaN
dtype: float64
0    5000.0
1    7000.0
3    9000.0
dtype: float64

In [ ]:
#manipulating data

In [ ]:
#replace values
import pandas as pd
s = pd.Series([5000,7000,None,9000,None])
print(s)

s= s.replace(5000,5500)
print(s)

0    5000.0
1    7000.0
2       NaN
3    9000.0
4       NaN
dtype: float64
0    5500.0
1    7000.0
2       NaN
3    9000.0
4       NaN
dtype: float64

In [ ]:
#create a data frame
import pandas as pd

data =[
    ["ravi ",22,30000],
    ["priya",21,40000],
    ["arun",23,28000]
]

df = pd.DataFrame(data)
print(df)

       0   1      2
0  ravi   22  30000
1  priya  21  40000
2   arun  23  28000

In [ ]:
#creating dataframe with tuple
import pandas as pd
data = (
    ("ravi",22,30000),
    ("priya",21,40000),
    ("arun",20,28000)
)

df = pd.DataFrame(data)
print(df)

       0   1      2
0   ravi  22  30000
1  priya  21  40000
2   arun  20  28000

In [ ]:
#list of set
import pandas as pd
my_set ={100,200,300,400}

df_from_set = pd.DataFrame(
    list(my_set),

)
print(df_from_set)

     0
0  200
1  100
2  400
3  300

In [ ]:
#create a dataframe with dictionary
import pandas as pd
data = {
    'name': ['alice','bob','charlie'],
    'age': [25,30,35],
    'city': ['NY','LA','Chicago']
}

df = pd.DataFrame(data)
print(df)

      name  age     city
0    alice   25       NY
1      bob   30       LA
2  charlie   35  Chicago

In [ ]:
#converting a series to a dataframe
s = pd.Series(
    [1,2,3,4],
    name='Numbers'
)
df = s.to_frame
print(df)

<bound method Series.to_frame of 0    1
1    2
2    3
3    4
Name: Numbers, dtype: int64>

In [ ]:
s1 = pd.Series(
    [1,2,3,4],
    s2 = pd.Series([9,6,5,8]),
    s3 = pd.Series([12,13,14,15]),
    name='Numbers'
)
df = s.to_frame(s1,s2,)
print(df)

TypeError: Series.__init__() got an unexpected keyword argument 's2'

In [ ]:
#create a series using loc
import pandas as pd
s = pd.Series(
    [5000,7000,6000,9000,8000],
    index=["monday","tuesday","wednusday","thursday","friday"]

)
print(s)
s.iloc[0:3]
s.loc["monday"]

monday       5000
tuesday      7000
wednusday    6000
thursday     9000
friday       8000
dtype: int64

np.int64(5000)

In [ ]:
import pandas as pd
s = pd.Series(
    [5000,7000,6000,9000,8000],
    index=["monday","tuesday","wednusday","thursday","friday"]

)
print(s)
s.max()
s.min()
s.sum()
s.median()
s.std()
s.mean()

monday       5000
tuesday      7000
wednusday    6000
thursday     9000
friday       8000
dtype: int64

np.float64(7000.0)

In [ ]:
import pandas as pd
data = {
    "name":["ravi","priya","arun","sneha","kiran","anjali","vikram","meena"],
    "age":[22,24,None,25,None,26,20,27],
    "city":["hyderabad","chennai","banglore","hyderabad","mumbai",None,"banglore","hyderabad"],
    "salary":[3000,4000,28000,5000,35000,45000,None,55000]
}
df = pd.DataFrame(data)
print(df)
df.iloc[0:3]
df.loc[0]

     name   age       city   salary
0    ravi  22.0  hyderabad   3000.0
1   priya  24.0    chennai   4000.0
2    arun   NaN   banglore  28000.0
3   sneha  25.0  hyderabad   5000.0
4   kiran   NaN     mumbai  35000.0
5  anjali  26.0       None  45000.0
6  vikram  20.0   banglore      NaN
7   meena  27.0  hyderabad  55000.0

name           ravi
age            22.0
city      hyderabad
salary       3000.0
Name: 0, dtype: object

In [ ]:
import pandas as pd
data = {
    "name":["ravi","priya","arun","sneha","kiran","anjali","vikram","meena"],
    "age":[22,24,None,25,None,26,20,27],
    "city":["hyderabad","chennai","banglore","hyderabad","mumbai",None,"banglore","hyderabad"],
    "salary":[3000,4000,28000,5000,35000,45000,None,55000]
}
i = [101,102,103,104,105,106,107,108]
df = pd.DataFrame(data,index =i)
print(df)
df.iloc[0:3]
df.loc[101:103]

       name   age       city   salary
101    ravi  22.0  hyderabad   3000.0
102   priya  24.0    chennai   4000.0
103    arun   NaN   banglore  28000.0
104   sneha  25.0  hyderabad   5000.0
105   kiran   NaN     mumbai  35000.0
106  anjali  26.0       None  45000.0
107  vikram  20.0   banglore      NaN
108   meena  27.0  hyderabad  55000.0

      name   age       city   salary
101   ravi  22.0  hyderabad   3000.0
102  priya  24.0    chennai   4000.0
103   arun   NaN   banglore  28000.0

In [ ]:
import pandas as pd
data = {
    "name":["ravi","priya","arun","sneha","kiran","anjali","vikram","meena"],
    "age":[22,24,None,25,None,26,20,27],
    "city":["hyderabad","chennai","banglore","hyderabad","mumbai",None,"banglore","hyderabad"],
    "salary":[3000,4000,28000,5000,35000,45000,None,55000]
}
i = [101,102,103,104,105,106,107,108]
df = pd.DataFrame(data,index =i)
print(df)
df.mean
df.max
df.count
df.median
df.sum

       name   age       city   salary
101    ravi  22.0  hyderabad   3000.0
102   priya  24.0    chennai   4000.0
103    arun   NaN   banglore  28000.0
104   sneha  25.0  hyderabad   5000.0
105   kiran   NaN     mumbai  35000.0
106  anjali  26.0       None  45000.0
107  vikram  20.0   banglore      NaN
108   meena  27.0  hyderabad  55000.0

<bound method DataFrame.sum of        name   age       city   salary
101    ravi  22.0  hyderabad   3000.0
102   priya  24.0    chennai   4000.0
103    arun   NaN   banglore  28000.0
104   sneha  25.0  hyderabad   5000.0
105   kiran   NaN     mumbai  35000.0
106  anjali  26.0       None  45000.0
107  vikram  20.0   banglore      NaN
108   meena  27.0  hyderabad  55000.0>

In [ ]:
import pandas as pd
data = {
    "name":["ravi","priya","arun","sneha","kiran","anjali","vikram","meena"],
    "age":[22,24,None,25,None,26,20,27],
    "city":["hyderabad","chennai","banglore","hyderabad","mumbai",None,"banglore","hyderabad"],
    "salary":[3000,4000,28000,5000,35000,45000,None,55000]
}
i = [101,102,103,104,105,106,107,108]
df = pd.DataFrame(data,index =i)
print(df)
df.median

SyntaxError: invalid syntax (552670341.py, line 11)

In [ ]:
import pandas as pd
s1 = pd.Series([100,200,300])
s2 = pd.Series([400,500,600])
print(s1)
print(s2)
r = pd.concat([s1,s2],ignore_index=True)
print(r)

0    100
1    200
2    300
dtype: int64
0    400
1    500
2    600
dtype: int64
0    100
1    200
2    300
3    400
4    500
5    600
dtype: int64

In [ ]:
#pd merge uses for concat

'''Date(index)     sales(data)
01-Aug              25000
02-Aug              28000
03-aug              32000
04-aug              NaN
05-aug              35000
06-aug             38000
07-aug              NaN
08-aug             42000
09-Aug              45000
10-aug              48000'''

In [ ]:
import pandas as pd
index =[1,2,3,4,5,6,7,8,9,10]
data =[25000,28000,32000,None,35000,38000,None,42000,45000,48000]
s = pd.Series(data,index)
print(s)
s.isna()

1     25000.0
2     28000.0
3     32000.0
4         NaN
5     35000.0
6     38000.0
7         NaN
8     42000.0
9     45000.0
10    48000.0
dtype: float64

1     False
2     False
3     False
4      True
5     False
6     False
7      True
8     False
9     False
10    False
dtype: bool

In [ ]:
import pandas as pd
index =[1,2,3,4,5,6,7,8,9,10]
data =[25000,28000,32000,None,35000,38000,None,42000,45000,48000]
s = pd.Series(data,index)
print(s)
s.isna()
s.fillna(s.mean())
s.replace()
s.sum()
s.tail()
s.head()
s.max()
s.min()
s.mean()

1     25000.0
2     28000.0
3     32000.0
4         NaN
5     35000.0
6     38000.0
7         NaN
8     42000.0
9     45000.0
10    48000.0
dtype: float64

/tmp/ipykernel_455/1165711517.py:8: FutureWarning: Series.replace without 'value' and with non-dict-like 'to_replace' is deprecated and will raise in a future version. Explicitly specify the new values instead.
  s.replace()
/tmp/ipykernel_455/1165711517.py:15: FutureWarning: Series.replace without 'value' and with non-dict-like 'to_replace' is deprecated and will raise in a future version. Explicitly specify the new values instead.
  s= s.replace(32000)

In [ ]:
import pandas as pd
months =["january","february","march","april","may","june","july","august","september","october"]
data =[120000,135000,None,150000,165000,None,180000,195000,210000,225000]
s = pd.Series(data,index=months)
print(s)
s.head(5)
s.tail(3)
print(s[['january','march','may']])
s>170000
s.isna()
s.isna().sum()
s.fillna
s.sum()
s.mean()
s.max()
s.min()

january      120000.0
february     135000.0
march             NaN
april        150000.0
may          165000.0
june              NaN
july         180000.0
august       195000.0
september    210000.0
october      225000.0
dtype: float64
january    120000.0
march           NaN
may        165000.0
dtype: float64

120000.0

In [ ]:
#converting a series into a dataframe
import pandas as pd
s = pd.Series(
    [1,2,3,4],
    name ='numbers'
)
s2 = pd.Series([9,6,5,8])
s3 = pd.Series([12,13,14,15])

df = s.to_frame()
d = {
    "name":s,
    "age":s2,
    "marks":s3
}
df = pd.DataFrame(d)


print(df)

   name  age  marks
0     1    9     12
1     2    6     13
2     3    5     14
3     4    8     15

In [ ]:
s = pd.Series(
    [1,2,3,4,5],
    name ='numbers'

)
s2 = pd.Series([9,6,5,8])
s3 = pd.Series([12,13,14,15])

df = s.to_frame()
df.head(3)
df.tail(2)
df.info()
df.describe()
df['numbers']



print(df)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 1 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   numbers  5 non-null      int64
dtypes: int64(1)
memory usage: 172.0 bytes
   numbers
0        1
1        2
2        3
3        4
4        5

In [ ]:
#renaming the single column
s = pd.Series([1,2,3,4],
              name = 'numbers'
              )
df = s.to_frame()
df.columns = ['digits']
print(df)

   digits
0       1
1       2
2       3
3       4

In [ ]:
#renaming existing columns

df.rename(
    columns={
        'A':'Alpha',
        'B':'Beta'
    },
    inplace = True
)

print(df)

   digits
0       1
1       2
2       3
3       4

In [ ]:
months =["january","february","march","april","may","june","july","august","september","october"]
data =[120000,135000,None,150000,165000,None,180000,195000,210000,225000]
s = pd.Series(data,index=months)
print(s)
df.head()
df.describe()
df.iloc[0]


print(df)

january      120000.0
february     135000.0
march             NaN
april        150000.0
may          165000.0
june              NaN
july         180000.0
august       195000.0
september    210000.0
october      225000.0
dtype: float64
   numbers
0        1
1        2
2        3
3        4
4        5

In [ ]:
data = {
    "name":["ravi","priya","arun","sneha","kiran","anjali","vikram","meena"],
    "age":[22,24,None,25,None,26,20,27],
    "city":["hyderabad","chennai","banglore","hyderabad","mumbai",None,"banglore","hyderabad"],
    "salary":[3000,4000,28000,5000,35000,45000,None,55000]
}
df = pd.DataFrame(data)
df.iloc[0:3]
df.loc[0]
print(df)

     name   age       city   salary
0    ravi  22.0  hyderabad   3000.0
1   priya  24.0    chennai   4000.0
2    arun   NaN   banglore  28000.0
3   sneha  25.0  hyderabad   5000.0
4   kiran   NaN     mumbai  35000.0
5  anjali  26.0       None  45000.0
6  vikram  20.0   banglore      NaN
7   meena  27.0  hyderabad  55000.0

In [ ]:
data = {
    "name":["ravi","priya","arun","sneha","kiran","anjali","vikram","meena"],
    "age":[22,24,None,25,None,26,20,27],
    "city":["hyderabad","chennai","banglore","hyderabad","mumbai",None,"banglore","hyderabad"],
    "salary":[3000,4000,28000,5000,35000,45000,None,55000]
}
df = pd.DataFrame(data)
print(df)
df.iloc[0:3]
df.loc[0]
print("________________________________")
e = df["age"]>21
print(e)
print("_________________________________")
d = df[df["age"]>21]
print(d)
print("_______________________________")
f =df["salary"]>40000
print(f)
print("__________________________")
g =df[df["city"]== "hyderabad"]
print(g)
print("__________________________")
result = df[
    (df['age']>23) &
    (df['city']=='hyderabad')
]
print(result)
print("__________________________")

r=df[
    (df["city"]=="mumbai") |
    (df["salary"]>45000)
]
print(r)

     name   age       city   salary
0    ravi  22.0  hyderabad   3000.0
1   priya  24.0    chennai   4000.0
2    arun   NaN   banglore  28000.0
3   sneha  25.0  hyderabad   5000.0
4   kiran   NaN     mumbai  35000.0
5  anjali  26.0       None  45000.0
6  vikram  20.0   banglore      NaN
7   meena  27.0  hyderabad  55000.0
________________________________
0     True
1     True
2    False
3     True
4    False
5     True
6    False
7     True
Name: age, dtype: bool
_________________________________
     name   age       city   salary
0    ravi  22.0  hyderabad   3000.0
1   priya  24.0    chennai   4000.0
3   sneha  25.0  hyderabad   5000.0
5  anjali  26.0       None  45000.0
7   meena  27.0  hyderabad  55000.0
_______________________________
0    False
1    False
2    False
3    False
4    False
5     True
6    False
7     True
Name: salary, dtype: bool
__________________________
    name   age       city   salary
0   ravi  22.0  hyderabad   3000.0
3  sneha  25.0  hyderabad   5000.0
7  meena  27.0  hyderabad  55000.0
__________________________
    name   age       city   salary
3  sneha  25.0  hyderabad   5000.0
7  meena  27.0  hyderabad  55000.0
__________________________
    name   age       city   salary
4  kiran   NaN     mumbai  35000.0
7  meena  27.0  hyderabad  55000.0

In [ ]:
data = {
    "name":["ravi","priya","arun","sneha","kiran","anjali","vikram","meena"],
    "age":[22,24,None,25,None,26,20,27],
    "city":["hyderabad","chennai","banglore","hyderabad","mumbai",None,"banglore","hyderabad"],
    "salary":[3000,4000,28000,5000,35000,45000,None,55000]
}
df.fillna({
    'age':0,
    'city': 'unknown'
}
)

       Index
0     Monday
1    Tuesday
2  Wednesday
3   Thursday
4     Friday
5     Sunday

In [ ]:
import pandas as pd
Data = {
    "Data" : [5000, 7000, None ,8000, None, 9000],

   "Index" : ["Monday", "Tuesday" , "Wednesday", "Thursday","Friday", "Sunday"]
}
df = pd.DataFrame(Data)
df.isna().sum()
print(df.dropna())

     Data     Index
0  5000.0    Monday
1  7000.0   Tuesday
3  8000.0  Thursday
5  9000.0    Sunday

In [ ]:
Data = {
    "Data" : [5000, 7000, None ,8000, None, 9000],

   "Index" : ["Monday", "Tuesday" , "Wednesday", "Thursday","Friday", "Sunday"]
}
df.dropna(axis=1,inplace=True)

print(df)

       Index
0     Monday
1    Tuesday
2  Wednesday
3   Thursday
4     Friday
5     Sunday

In [ ]:
data = {

    "name":["ravi","priya","arun","sneha","kiran","anjali","vikram","meena"],
    "age":[22,24,None,25,None,26,20,27],
    "city":["hyderabad","chennai","banglore","hyderabad","mumbai",None,"banglore","hyderabad"],
    "salary":[3000,4000,28000,5000,35000,45000,None,55000]
}
df = pd.DataFrame(data)
print(df)
df.iloc[0:3]
df.loc[0]
print("________________________________")
e = df["age"]>21
print(e)
print("_________________________________")
d = df[df["age"]>21]
print(d)
print("_______________________________")
f =df["salary"]>40000
print(f)
print("__________________________")
g =df[df["city"]== "hyderabad"]
print(g)
print("__________________________")
result = df[
    (df['age']>23) &
    (df['city']=='hyderabad')
]
print(result)
print("__________________________")

r=df[
    (df["city"]=="mumbai") |
    (df["salary"]>45000)
]
print(r)

df.fillna({
    'age':0,
    'city': 'unknown'
}
)

     name   age       city   salary
0    ravi  22.0  hyderabad   3000.0
1   priya  24.0    chennai   4000.0
2    arun   NaN   banglore  28000.0
3   sneha  25.0  hyderabad   5000.0
4   kiran   NaN     mumbai  35000.0
5  anjali  26.0       None  45000.0
6  vikram  20.0   banglore      NaN
7   meena  27.0  hyderabad  55000.0
________________________________
0     True
1     True
2    False
3     True
4    False
5     True
6    False
7     True
Name: age, dtype: bool
_________________________________
     name   age       city   salary
0    ravi  22.0  hyderabad   3000.0
1   priya  24.0    chennai   4000.0
3   sneha  25.0  hyderabad   5000.0
5  anjali  26.0       None  45000.0
7   meena  27.0  hyderabad  55000.0
_______________________________
0    False
1    False
2    False
3    False
4    False
5     True
6    False
7     True
Name: salary, dtype: bool
__________________________
    name   age       city   salary
0   ravi  22.0  hyderabad   3000.0
3  sneha  25.0  hyderabad   5000.0
7  meena  27.0  hyderabad  55000.0
__________________________
    name   age       city   salary
3  sneha  25.0  hyderabad   5000.0
7  meena  27.0  hyderabad  55000.0
__________________________
    name   age       city   salary
4  kiran   NaN     mumbai  35000.0
7  meena  27.0  hyderabad  55000.0

     name   age       city   salary
0    ravi  22.0  hyderabad   3000.0
1   priya  24.0    chennai   4000.0
2    arun   0.0   banglore  28000.0
3   sneha  25.0  hyderabad   5000.0
4   kiran   0.0     mumbai  35000.0
5  anjali  26.0    unknown  45000.0
6  vikram  20.0   banglore      NaN
7   meena  27.0  hyderabad  55000.0

In [ ]:
data = {

    "name":["ravi","priya","arun","sneha","kiran","anjali","vikram","meena"],
    "age":[22,24,None,25,None,26,20,27],
    "city":["hyderabad","chennai","banglore","hyderabad","mumbai",None,"banglore","hyderabad"],
    "salary":[3000,4000,28000,5000,35000,45000,None,55000]
}
df = pd.DataFrame(data)

df['age'] == df['age'].fillna(
    df['age'].mean()
)
print(df)

     name   age       city   salary
0    ravi  22.0  hyderabad   3000.0
1   priya  24.0    chennai   4000.0
2    arun   NaN   banglore  28000.0
3   sneha  25.0  hyderabad   5000.0
4   kiran   NaN     mumbai  35000.0
5  anjali  26.0       None  45000.0
6  vikram  20.0   banglore      NaN
7   meena  27.0  hyderabad  55000.0

In [ ]:
emp_details = {
    "EmpID":[101,102,103,104,101],
    "city":["hyderabad","chennai","banglore",None,"hyderabad"],
    "Experience":[None,4,3,5,2],
    "age":[25,30,None,35,25]
}
df = pd.DataFrame(emp_details)
print(df)
df.isna().sum()
df['age'] == df['age'].fillna(
    df['age'].median()
)
df.fillna{'city':unknown,'experience':0}

df["salary"=[1000,]]
print(df)

SyntaxError: invalid syntax (2190145986.py, line 13)

In [ ]:
data = {

    "name":["ravi","priya","arun","sneha","kiran","anjali","vikram","meena"],
    "age":[22,24,None,25,None,26,20,27],
    "city":["hyderabad","chennai","banglore","hyderabad","mumbai",None,"banglore","hyderabad"],
    "salary":[3000,4000,28000,5000,35000,45000,None,55000]
}
df = pd.DataFrame(data)

df['age'] == df['age'].fillna(
    df['age'].median()
)
df.loc[len(df)]=['ram','pune',4,25,56000]


print(df)

ValueError: cannot set a row with mismatched columns

In [ ]:
data = {

    "name":["ravi","priya","arun","sneha","kiran","anjali","vikram","meena"],
    "age":[22,24,None,25,None,26,20,27],
    "city":["hyderabad","chennai","banglore","hyderabad","mumbai",None,"banglore","hyderabad"],
    "salary":[3000,4000,28000,5000,35000,45000,None,55000]
}
df = pd.DataFrame(data)
df.dropna(axis=0,inplace=True)

print(df)

ValueError: cannot set a row with mismatched columns

In [ ]:
emp_details = {
    "EmpID":[101,102,103,104,101],
    "city":["hyderabad","chennai","banglore",None,"hyderabad"],
    "Experience":[None,4,3,5,2],
    "age":[25,30,None,35,25]
}
df = pd.DataFrame(emp_details)

df["salary"]=[1000,2000,3000,4000,None]

df["Bonus"]=df["salary"]*0.10
df.drop('Bonus',
        axis=1,
        inplace=True
)
df.drop(
    columns=['salary'],
    inplace=True
)
df.drop(2,
        axis=0,
        inplace=True)

df.groupby('city')['age'].mean()

print(df)

   EmpID       city  Experience   age
0    101  hyderabad         NaN  25.0
1    102    chennai         4.0  30.0
3    104       None         5.0  35.0
4    101  hyderabad         2.0  25.0

In [ ]:
emp_details = {
    "EmpID":[101,102,103,104,101],
    "city":["hyderabad","chennai","banglore",None,"hyderabad"],
    "Experience":[None,4,3,5,2],
    "age":[25,30,None,35,25]
}
df = pd.DataFrame(emp_details)
print(df)
df.groupby('city')['age'].mean()
df.groupby('city')['age'].max()
df.groupby('city')['age'].median()
df.groupby('city')['age'].count()

   EmpID       city  Experience   age
0    101  hyderabad         NaN  25.0
1    102    chennai         4.0  30.0
2    103   banglore         3.0   NaN
3    104       None         5.0  35.0
4    101  hyderabad         2.0  25.0

city
banglore     0
chennai      1
hyderabad    2
Name: age, dtype: int64

In [ ]:
import pandas as pd
data = {
    "Name":["Ravi","Priya","Arun","Sneha","Kiran","Anjali","Vikram","Meena"],
    "Age":[22,24,21,25,23,26,20,27],
    "City":["Hyderabad","Chennai","Bangalore","Hyderabad","Mumbai","Chennai","Bengalore","Mumbai"],
    "Salary":[30000,40000,28000,50000,35000,45000,25000,55000]
}
df=pd.DataFrame(data)
print(df)
print(df["Name"])
print(df[["Name","Salary"]])
print(df[df["Age"]>23])
print(df[df["Salary"]>40000])

     Name  Age       City  Salary
0    Ravi   22  Hyderabad   30000
1   Priya   24    Chennai   40000
2    Arun   21  Bangalore   28000
3   Sneha   25  Hyderabad   50000
4   Kiran   23     Mumbai   35000
5  Anjali   26    Chennai   45000
6  Vikram   20  Bengalore   25000
7   Meena   27     Mumbai   55000
0      Ravi
1     Priya
2      Arun
3     Sneha
4     Kiran
5    Anjali
6    Vikram
7     Meena
Name: Name, dtype: object
     Name  Salary
0    Ravi   30000
1   Priya   40000
2    Arun   28000
3   Sneha   50000
4   Kiran   35000
5  Anjali   45000
6  Vikram   25000
7   Meena   55000
     Name  Age       City  Salary
1   Priya   24    Chennai   40000
3   Sneha   25  Hyderabad   50000
5  Anjali   26    Chennai   45000
7   Meena   27     Mumbai   55000
     Name  Age       City  Salary
3   Sneha   25  Hyderabad   50000
5  Anjali   26    Chennai   45000
7   Meena   27     Mumbai   55000

In [ ]:
df1 = pd.DataFrame({'ID':[1,2,3],
                    'Name':['A','B','C']})
df2 = pd.DataFrame({'ID':[1,2,4],
                    'Salary':[100,200,300]})
merged = pd.merge(df1,df2,on='ID',how='inner')
print(merged)
print("_____________________________")
merged = pd.merge(df1,df2,on='ID',how='left')
print(merged)
print("_____________________________")
merged = pd.merge(df1,df2,on='ID',how='right')
print(merged)
print("_____________________________")
merged = pd.merge(df1,df2,on='ID',how='inner')
print(merged)
#concat
#vertically-add rows
#horizontally-add columns
print("_____________________________")
combined = pd.concat([df1,df2],axis=0,ignore_index=True)
print(combined)
print("_____________________________")
combined = pd.concat([df1,df2],axis=1)
print(combined)
#on data frames manupulations completed- joing adding removing cleaning all

   ID Name  Salary
0   1    A     100
1   2    B     200
_____________________________
   ID Name  Salary
0   1    A   100.0
1   2    B   200.0
2   3    C     NaN
_____________________________
   ID Name  Salary
0   1    A     100
1   2    B     200
2   4  NaN     300
_____________________________
   ID Name  Salary
0   1    A     100
1   2    B     200
_____________________________
   ID Name  Salary
0   1    A     NaN
1   2    B     NaN
2   3    C     NaN
3   1  NaN   100.0
4   2  NaN   200.0
5   4  NaN   300.0
_____________________________
   ID Name  ID  Salary
0   1    A   1     100
1   2    B   2     200
2   3    C   4     300

In [ ]:
df = pd.read_csv('/content/sample_data/mnist_test.csv')
print(df)
print("_____________________________________________________")
print(df.head())
print("_____________________________________________________")
print(df.tail())
print("_____________________________________________________")
print(df.shape)
print(df.isna)

      7  0  0.1  0.2  0.3  0.4  0.5  0.6  0.7  0.8  ...  0.658  0.659  0.660  \
0     2  0    0    0    0    0    0    0    0    0  ...      0      0      0
1     1  0    0    0    0    0    0    0    0    0  ...      0      0      0
2     0  0    0    0    0    0    0    0    0    0  ...      0      0      0
3     4  0    0    0    0    0    0    0    0    0  ...      0      0      0
4     1  0    0    0    0    0    0    0    0    0  ...      0      0      0
...  .. ..  ...  ...  ...  ...  ...  ...  ...  ...  ...    ...    ...    ...
9994  2  0    0    0    0    0    0    0    0    0  ...      0      0      0
9995  3  0    0    0    0    0    0    0    0    0  ...      0      0      0
9996  4  0    0    0    0    0    0    0    0    0  ...      0      0      0
9997  5  0    0    0    0    0    0    0    0    0  ...      0      0      0
9998  6  0    0    0    0    0    0    0    0    0  ...      0      0      0

      0.661  0.662  0.663  0.664  0.665  0.666  0.667
0         0      0      0      0      0      0      0
1         0      0      0      0      0      0      0
2         0      0      0      0      0      0      0
3         0      0      0      0      0      0      0
4         0      0      0      0      0      0      0
...     ...    ...    ...    ...    ...    ...    ...
9994      0      0      0      0      0      0      0
9995      0      0      0      0      0      0      0
9996      0      0      0      0      0      0      0
9997      0      0      0      0      0      0      0
9998      0      0      0      0      0      0      0

[9999 rows x 785 columns]
_____________________________________________________
   7  0  0.1  0.2  0.3  0.4  0.5  0.6  0.7  0.8  ...  0.658  0.659  0.660  \
0  2  0    0    0    0    0    0    0    0    0  ...      0      0      0
1  1  0    0    0    0    0    0    0    0    0  ...      0      0      0
2  0  0    0    0    0    0    0    0    0    0  ...      0      0      0
3  4  0    0    0    0    0    0    0    0    0  ...      0      0      0
4  1  0    0    0    0    0    0    0    0    0  ...      0      0      0

   0.661  0.662  0.663  0.664  0.665  0.666  0.667
0      0      0      0      0      0      0      0
1      0      0      0      0      0      0      0
2      0      0      0      0      0      0      0
3      0      0      0      0      0      0      0
4      0      0      0      0      0      0      0

[5 rows x 785 columns]
_____________________________________________________
      7  0  0.1  0.2  0.3  0.4  0.5  0.6  0.7  0.8  ...  0.658  0.659  0.660  \
9994  2  0    0    0    0    0    0    0    0    0  ...      0      0      0
9995  3  0    0    0    0    0    0    0    0    0  ...      0      0      0
9996  4  0    0    0    0    0    0    0    0    0  ...      0      0      0
9997  5  0    0    0    0    0    0    0    0    0  ...      0      0      0
9998  6  0    0    0    0    0    0    0    0    0  ...      0      0      0

      0.661  0.662  0.663  0.664  0.665  0.666  0.667
9994      0      0      0      0      0      0      0
9995      0      0      0      0      0      0      0
9996      0      0      0      0      0      0      0
9997      0      0      0      0      0      0      0
9998      0      0      0      0      0      0      0

[5 rows x 785 columns]
_____________________________________________________
(9999, 785)
<bound method DataFrame.isna of       7  0  0.1  0.2  0.3  0.4  0.5  0.6  0.7  0.8  ...  0.658  0.659  0.660  \
0     2  0    0    0    0    0    0    0    0    0  ...      0      0      0
1     1  0    0    0    0    0    0    0    0    0  ...      0      0      0
2     0  0    0    0    0    0    0    0    0    0  ...      0      0      0
3     4  0    0    0    0    0    0    0    0    0  ...      0      0      0
4     1  0    0    0    0    0    0    0    0    0  ...      0      0      0
...  .. ..  ...  ...  ...  ...  ...  ...  ...  ...  ...    ...    ...    ...
9994  2  0    0    0    0    0    0    0    0    0  ...      0      0      0
9995  3  0    0    0    0    0    0    0    0    0  ...      0      0      0
9996  4  0    0    0    0    0    0    0    0    0  ...      0      0      0
9997  5  0    0    0    0    0    0    0    0    0  ...      0      0      0
9998  6  0    0    0    0    0    0    0    0    0  ...      0      0      0

      0.661  0.662  0.663  0.664  0.665  0.666  0.667
0         0      0      0      0      0      0      0
1         0      0      0      0      0      0      0
2         0      0      0      0      0      0      0
3         0      0      0      0      0      0      0
4         0      0      0      0      0      0      0
...     ...    ...    ...    ...    ...    ...    ...
9994      0      0      0      0      0      0      0
9995      0      0      0      0      0      0      0
9996      0      0      0      0      0      0      0
9997      0      0      0      0      0      0      0
9998      0      0      0      0      0      0      0

[9999 rows x 785 columns]>

In [ ]:
import pandas as pd
df = pd.read_csv('/content/sample_data/mnist_test.csv')
print("____________________________________")
print(df.head())
print("_______________________________________")
print(df.tail())
print(df.isna)
print(df)

____________________________________
   7  0  0.1  0.2  0.3  0.4  0.5  0.6  0.7  0.8  ...  0.658  0.659  0.660  \
0  2  0    0    0    0    0    0    0    0    0  ...      0      0      0
1  1  0    0    0    0    0    0    0    0    0  ...      0      0      0
2  0  0    0    0    0    0    0    0    0    0  ...      0      0      0
3  4  0    0    0    0    0    0    0    0    0  ...      0      0      0
4  1  0    0    0    0    0    0    0    0    0  ...      0      0      0

   0.661  0.662  0.663  0.664  0.665  0.666  0.667
0      0      0      0      0      0      0      0
1      0      0      0      0      0      0      0
2      0      0      0      0      0      0      0
3      0      0      0      0      0      0      0
4      0      0      0      0      0      0      0

[5 rows x 785 columns]
_______________________________________
      7  0  0.1  0.2  0.3  0.4  0.5  0.6  0.7  0.8  ...  0.658  0.659  0.660  \
9994  2  0    0    0    0    0    0    0    0    0  ...      0      0      0
9995  3  0    0    0    0    0    0    0    0    0  ...      0      0      0
9996  4  0    0    0    0    0    0    0    0    0  ...      0      0      0
9997  5  0    0    0    0    0    0    0    0    0  ...      0      0      0
9998  6  0    0    0    0    0    0    0    0    0  ...      0      0      0

      0.661  0.662  0.663  0.664  0.665  0.666  0.667
9994      0      0      0      0      0      0      0
9995      0      0      0      0      0      0      0
9996      0      0      0      0      0      0      0
9997      0      0      0      0      0      0      0
9998      0      0      0      0      0      0      0

[5 rows x 785 columns]
<bound method DataFrame.isna of       7  0  0.1  0.2  0.3  0.4  0.5  0.6  0.7  0.8  ...  0.658  0.659  0.660  \
0     2  0    0    0    0    0    0    0    0    0  ...      0      0      0
1     1  0    0    0    0    0    0    0    0    0  ...      0      0      0
2     0  0    0    0    0    0    0    0    0    0  ...      0      0      0
3     4  0    0    0    0    0    0    0    0    0  ...      0      0      0
4     1  0    0    0    0    0    0    0    0    0  ...      0      0      0
...  .. ..  ...  ...  ...  ...  ...  ...  ...  ...  ...    ...    ...    ...
9994  2  0    0    0    0    0    0    0    0    0  ...      0      0      0
9995  3  0    0    0    0    0    0    0    0    0  ...      0      0      0
9996  4  0    0    0    0    0    0    0    0    0  ...      0      0      0
9997  5  0    0    0    0    0    0    0    0    0  ...      0      0      0
9998  6  0    0    0    0    0    0    0    0    0  ...      0      0      0

      0.661  0.662  0.663  0.664  0.665  0.666  0.667
0         0      0      0      0      0      0      0
1         0      0      0      0      0      0      0
2         0      0      0      0      0      0      0
3         0      0      0      0      0      0      0
4         0      0      0      0      0      0      0
...     ...    ...    ...    ...    ...    ...    ...
9994      0      0      0      0      0      0      0
9995      0      0      0      0      0      0      0
9996      0      0      0      0      0      0      0
9997      0      0      0      0      0      0      0
9998      0      0      0      0      0      0      0

[9999 rows x 785 columns]>
      7  0  0.1  0.2  0.3  0.4  0.5  0.6  0.7  0.8  ...  0.658  0.659  0.660  \
0     2  0    0    0    0    0    0    0    0    0  ...      0      0      0
1     1  0    0    0    0    0    0    0    0    0  ...      0      0      0
2     0  0    0    0    0    0    0    0    0    0  ...      0      0      0
3     4  0    0    0    0    0    0    0    0    0  ...      0      0      0
4     1  0    0    0    0    0    0    0    0    0  ...      0      0      0
...  .. ..  ...  ...  ...  ...  ...  ...  ...  ...  ...    ...    ...    ...
9994  2  0    0    0    0    0    0    0    0    0  ...      0      0      0
9995  3  0    0    0    0    0    0    0    0    0  ...      0      0      0
9996  4  0    0    0    0    0    0    0    0    0  ...      0      0      0
9997  5  0    0    0    0    0    0    0    0    0  ...      0      0      0
9998  6  0    0    0    0    0    0    0    0    0  ...      0      0      0

      0.661  0.662  0.663  0.664  0.665  0.666  0.667
0         0      0      0      0      0      0      0
1         0      0      0      0      0      0      0
2         0      0      0      0      0      0      0
3         0      0      0      0      0      0      0
4         0      0      0      0      0      0      0
...     ...    ...    ...    ...    ...    ...    ...
9994      0      0      0      0      0      0      0
9995      0      0      0      0      0      0      0
9996      0      0      0      0      0      0      0
9997      0      0      0      0      0      0      0
9998      0      0      0      0      0      0      0

[9999 rows x 785 columns]

In [ ]:
df = pd.read_excel('/content/01 Retail Inventory.xlsx',
                   sheet_name='Retail Inventory'
)
print("___________________________________")
print(df.head())
print("________________________________")
print(df.tail())
print(df)

___________________________________
  Product ID     Product Name           Category          Supplier Name  \
0   PRD-1001     Wine Glasses     Home & Kitchen        Heritage Brands
1   PRD-1002         Eye Mask             Beauty        Coastal Trading
2   PRD-1003  Resistance Band  Sports & Outdoors  National Supply Group
3   PRD-1004    Action Figure       Toys & Games      Pacific Wholesale
4   PRD-1005     Serving Tray     Home & Kitchen        Coastal Trading

   Unit Cost  Retail Price  Opening Stock  Units Sold  Closing Stock  \
0      23.78         38.89            135         118             17
1      15.67         24.53             86          10             76
2       5.59         11.88            319         195            124
3       9.72         18.01            173         140             33
4       8.22         13.90             32           8             24

   Reorder Point Stock Status
0             30    Low Stock
1              9     In Stock
2             47     In Stock
3             39    Low Stock
4              7     In Stock
________________________________
    Product ID      Product Name        Category         Supplier Name  \
995   PRD-1996         Slime Kit    Toys & Games  Summit Wholesale Inc
996   PRD-1997       Utensil Set  Home & Kitchen        United Imports
997   PRD-1998  Wireless Earbuds     Electronics       Heritage Brands
998   PRD-1999        Hand Cream          Beauty     Pacific Wholesale
999   PRD-2000         Card Deck    Toys & Games    Metro Distributors

     Unit Cost  Retail Price  Opening Stock  Units Sold  Closing Stock  \
995      14.40         19.26             25          12             13
996       3.64          5.04            175          96             79
997      13.85         21.30            147          66             81
998      17.47         24.42            144         124             20
999       2.58          5.05            134          78             56

     Reorder Point Stock Status
995              2     In Stock
996             28     In Stock
997             21     In Stock
998             18     In Stock
999             24     In Stock
    Product ID      Product Name           Category          Supplier Name  \
0     PRD-1001      Wine Glasses     Home & Kitchen        Heritage Brands
1     PRD-1002          Eye Mask             Beauty        Coastal Trading
2     PRD-1003   Resistance Band  Sports & Outdoors  National Supply Group
3     PRD-1004     Action Figure       Toys & Games      Pacific Wholesale
4     PRD-1005      Serving Tray     Home & Kitchen        Coastal Trading
..         ...               ...                ...                    ...
995   PRD-1996         Slime Kit       Toys & Games   Summit Wholesale Inc
996   PRD-1997       Utensil Set     Home & Kitchen         United Imports
997   PRD-1998  Wireless Earbuds        Electronics        Heritage Brands
998   PRD-1999        Hand Cream             Beauty      Pacific Wholesale
999   PRD-2000         Card Deck       Toys & Games     Metro Distributors

     Unit Cost  Retail Price  Opening Stock  Units Sold  Closing Stock  \
0        23.78         38.89            135         118             17
1        15.67         24.53             86          10             76
2         5.59         11.88            319         195            124
3         9.72         18.01            173         140             33
4         8.22         13.90             32           8             24
..         ...           ...            ...         ...            ...
995      14.40         19.26             25          12             13
996       3.64          5.04            175          96             79
997      13.85         21.30            147          66             81
998      17.47         24.42            144         124             20
999       2.58          5.05            134          78             56

     Reorder Point Stock Status
0               30    Low Stock
1                9     In Stock
2               47     In Stock
3               39    Low Stock
4                7     In Stock
..             ...          ...
995              2     In Stock
996             28     In Stock
997             21     In Stock
998             18     In Stock
999             24     In Stock

[1000 rows x 11 columns]

In [ ]:
import pandas as pd
data = {
    "EmpID": [101,102,103,104,105,106,107,108,109,110,110],
    "Name":["Ravi","PRIYA","Arun", "Sneha","Kiran","ANJALI", "Vikram","meena","RAHUL","Sneha","Sneha"],
    "city":["Hyderabad","Hyderabad","CHENNAI","Chennai","Banglore","BANGLORE","mumbai","mumbai","Delhi","HYDERABAD","HYDERABAD"],
    "salary":[30000,40000,3500,32000,45000,50000,38000,42000,36000,45000,45000]
}
df = pd.DataFrame(data)
print(df)
df.duplicated()
print("__________________________")
duplicates = df[df.duplicated()]
print(duplicates)
print("_________________________")
duplicates = df[df.duplicated(keep=False)]
print(duplicates)
d= df[df.duplicated(keep = False)]
total =d["salary"].sum()
print(total)
df["city"].duplicated()
duplicates = df[df["EmpID"].duplicated()]
print(duplicates)
df[df["EmpID"].duplicated()]
print(duplicates)
duplicates = df[df["Name"].duplicated(keep=False)]
print(duplicates)
df = df.drop_duplicates(keep="last")
print(df)
duplicates = df[df["Name"].duplicated(keep=False)]
print(duplicates)
df["city"]== df["city"].str.upper()
print(df)

    EmpID    Name       city  salary
0     101    Ravi  Hyderabad   30000
1     102   PRIYA  Hyderabad   40000
2     103    Arun    CHENNAI    3500
3     104   Sneha    Chennai   32000
4     105   Kiran   Banglore   45000
5     106  ANJALI   BANGLORE   50000
6     107  Vikram     mumbai   38000
7     108   meena     mumbai   42000
8     109   RAHUL      Delhi   36000
9     110   Sneha  HYDERABAD   45000
10    110   Sneha  HYDERABAD   45000
__________________________
    EmpID   Name       city  salary
10    110  Sneha  HYDERABAD   45000
_________________________
    EmpID   Name       city  salary
9     110  Sneha  HYDERABAD   45000
10    110  Sneha  HYDERABAD   45000
90000
    EmpID   Name       city  salary
10    110  Sneha  HYDERABAD   45000
    EmpID   Name       city  salary
10    110  Sneha  HYDERABAD   45000
    EmpID   Name       city  salary
3     104  Sneha    Chennai   32000
9     110  Sneha  HYDERABAD   45000
10    110  Sneha  HYDERABAD   45000
    EmpID    Name       city  salary
0     101    Ravi  Hyderabad   30000
1     102   PRIYA  Hyderabad   40000
2     103    Arun    CHENNAI    3500
3     104   Sneha    Chennai   32000
4     105   Kiran   Banglore   45000
5     106  ANJALI   BANGLORE   50000
6     107  Vikram     mumbai   38000
7     108   meena     mumbai   42000
8     109   RAHUL      Delhi   36000
10    110   Sneha  HYDERABAD   45000
    EmpID   Name       city  salary
3     104  Sneha    Chennai   32000
10    110  Sneha  HYDERABAD   45000
    EmpID    Name       city  salary
0     101    Ravi  Hyderabad   30000
1     102   PRIYA  Hyderabad   40000
2     103    Arun    CHENNAI    3500
3     104   Sneha    Chennai   32000
4     105   Kiran   Banglore   45000
5     106  ANJALI   BANGLORE   50000
6     107  Vikram     mumbai   38000
7     108   meena     mumbai   42000
8     109   RAHUL      Delhi   36000
10    110   Sneha  HYDERABAD   45000

In [ ]:
import pandas as pd

data = {

   "TransactionID": [1001, 1002, 1003, 1004, 1005,

                      1006, 1007, 1008, 1009, 1010, 1010, 1011],

   "Customer": ["Ravi", "Priya", "Arun", "Sneha", "Kiran",

                "Anjali", "Vikram", "Meena", "Rahul", "Sneha",

                "Sneha", "Kiran"],

   "Product": ["Laptop", "Mobile", "Tablet", "Headphones", "Mouse",

               "Keyboard", "Monitor", "Laptop", "Mobile", "Headphones",

               "Headphones", "Mouse"],

   "Amount": [55000, 25000, 30000, 5000, 1500,

              2500, 18000, 55000, 22000, 5000,

              5000, 1500]}

df= pd.DataFrame(data)
df.duplicated()
duplicates = df[df["TransactionID"].duplicated()]
print(duplicates)
d= df[df.duplicated(keep = False)]
total =d["Amount"].sum()
print(total)
d=df[df.duplicated(subset=['TransactionID'],keep=False)]
duplicates=df[df.duplicated(subset=['Customer'],keep=False)]
print(duplicates)
duplicates = df.drop_duplicates(keep="first")
print(duplicates)
print(df[df.duplicated(keep=False)])
print(duplicates)
duplicates=df.drop_duplicates(subset=["Customer","Product"],keep="first")
print(duplicates)
duplicates = df[df["TransactionID"].duplicated(keep=False)]
print(duplicates)
df["Customer"]== df["Customer"].str.upper()
df["Customer"]== df["Customer"].str.title()
df["Customer"]== df["Customer"].str.lower()
df["Product"]== df["Product"].str.lower()
df["Customer"]==df["Customer"].str.strip()
df["Product"]==df["Product"].str.title()
print(df)

    TransactionID Customer     Product  Amount
10           1010    Sneha  Headphones    5000
10000
    TransactionID Customer     Product  Amount
3            1004    Sneha  Headphones    5000
4            1005    Kiran       Mouse    1500
9            1010    Sneha  Headphones    5000
10           1010    Sneha  Headphones    5000
11           1011    Kiran       Mouse    1500
    TransactionID Customer     Product  Amount
0            1001     Ravi      Laptop   55000
1            1002    Priya      Mobile   25000
2            1003     Arun      Tablet   30000
3            1004    Sneha  Headphones    5000
4            1005    Kiran       Mouse    1500
5            1006   Anjali    Keyboard    2500
6            1007   Vikram     Monitor   18000
7            1008    Meena      Laptop   55000
8            1009    Rahul      Mobile   22000
9            1010    Sneha  Headphones    5000
11           1011    Kiran       Mouse    1500
    TransactionID Customer     Product  Amount
9            1010    Sneha  Headphones    5000
10           1010    Sneha  Headphones    5000
    TransactionID Customer     Product  Amount
0            1001     Ravi      Laptop   55000
1            1002    Priya      Mobile   25000
2            1003     Arun      Tablet   30000
3            1004    Sneha  Headphones    5000
4            1005    Kiran       Mouse    1500
5            1006   Anjali    Keyboard    2500
6            1007   Vikram     Monitor   18000
7            1008    Meena      Laptop   55000
8            1009    Rahul      Mobile   22000
9            1010    Sneha  Headphones    5000
11           1011    Kiran       Mouse    1500
   TransactionID Customer     Product  Amount
0           1001     Ravi      Laptop   55000
1           1002    Priya      Mobile   25000
2           1003     Arun      Tablet   30000
3           1004    Sneha  Headphones    5000
4           1005    Kiran       Mouse    1500
5           1006   Anjali    Keyboard    2500
6           1007   Vikram     Monitor   18000
7           1008    Meena      Laptop   55000
8           1009    Rahul      Mobile   22000
    TransactionID Customer     Product  Amount
9            1010    Sneha  Headphones    5000
10           1010    Sneha  Headphones    5000
    TransactionID Customer     Product  Amount
0            1001     Ravi      Laptop   55000
1            1002    Priya      Mobile   25000
2            1003     Arun      Tablet   30000
3            1004    Sneha  Headphones    5000
4            1005    Kiran       Mouse    1500
5            1006   Anjali    Keyboard    2500
6            1007   Vikram     Monitor   18000
7            1008    Meena      Laptop   55000
8            1009    Rahul      Mobile   22000
9            1010    Sneha  Headphones    5000
10           1010    Sneha  Headphones    5000
11           1011    Kiran       Mouse    1500

In [ ]:
import pandas as pd

data = {
 "VisitID": [501, 502, 503, 504, 505,506, 507, 508, 509, 510, 510, 511],
"Patient": ["Rahul", "Anita", "Suresh", "Priya", "Kiran","Anjali", "Ravi", "Meena", "Arun", "Priya","Priya", "Kiran"],
"Department": ["Cardiology", "Neurology", "Orthopedic", "General", "Dental", "Cardiology", "Neurology", "General","Dental", "Cardiology", "Cardiology", "Dental"],
 "BillAmount": [5000, 7500, 4500, 2000, 1500,6000, 7000, 2500, 1800, 6000,6000, 1500]}
df= pd.DataFrame(data)
print(df)
df = df.drop_duplicates(subset=["Patient"],keep="first")
print(df)
duplicates = df[df["BillAmount"].duplicated(keep=False)]
print(duplicates)
print(df)
df["Patient"]= df["Patient"].str.title()
df["Patient"]= df["Patient"].str.upper()
duplicates = df.drop_duplicates(keep="first")
duplicates = df[df["Department"].duplicated(keep=False)]
duplicates = df[df["Patient"].duplicated()]

print(df)

    VisitID Patient  Department  BillAmount
0       501   Rahul  Cardiology        5000
1       502   Anita   Neurology        7500
2       503  Suresh  Orthopedic        4500
3       504   Priya     General        2000
4       505   Kiran      Dental        1500
5       506  Anjali  Cardiology        6000
6       507    Ravi   Neurology        7000
7       508   Meena     General        2500
8       509    Arun      Dental        1800
9       510   Priya  Cardiology        6000
10      510   Priya  Cardiology        6000
11      511   Kiran      Dental        1500
   VisitID Patient  Department  BillAmount
0      501   Rahul  Cardiology        5000
1      502   Anita   Neurology        7500
2      503  Suresh  Orthopedic        4500
3      504   Priya     General        2000
4      505   Kiran      Dental        1500
5      506  Anjali  Cardiology        6000
6      507    Ravi   Neurology        7000
7      508   Meena     General        2500
8      509    Arun      Dental        1800
Empty DataFrame
Columns: [VisitID, Patient, Department, BillAmount]
Index: []
   VisitID Patient  Department  BillAmount
0      501   Rahul  Cardiology        5000
1      502   Anita   Neurology        7500
2      503  Suresh  Orthopedic        4500
3      504   Priya     General        2000
4      505   Kiran      Dental        1500
5      506  Anjali  Cardiology        6000
6      507    Ravi   Neurology        7000
7      508   Meena     General        2500
8      509    Arun      Dental        1800
   VisitID Patient  Department  BillAmount
0      501   RAHUL  Cardiology        5000
1      502   ANITA   Neurology        7500
2      503  SURESH  Orthopedic        4500
3      504   PRIYA     General        2000
4      505   KIRAN      Dental        1500
5      506  ANJALI  Cardiology        6000
6      507    RAVI   Neurology        7000
7      508   MEENA     General        2500
8      509    ARUN      Dental        1800

In [ ]:
import pandas as pd

data = {

   "TransactionID": [1001, 1002, 1003, 1004, 1005,

                      1006, 1007, 1008, 1009, 1010, 1010, 1011],

   "Customer": ["Ravi", "Priya", "Arun", "Sneha", "Kiran",

                "Anjali", "Vikram", "Meena", "Rahul", "Sneha",

                "Sneha", "Kiran"],

   "Product": ["Laptop", "Mobile", "Tablet", "Headphones", "Mouse",

               "Keyboard", "Monitor", "Laptop", "Mobile", "Headphones",

               "Headphones", "Mouse"],

   "Amount": [55000, 25000, 30000, 5000, 1500,

              2500, 18000, 55000, 22000, 5000,

              5000, 1500]}

df= pd.DataFrame(data)
print(df)
df["Customer"]= df["Customer"].str.upper()
df["Customer"]= df["Customer"].str.title()
df["Customer"]= df["Customer"].str.lower()
df["Product"]= df["Product"].str.lower()
df["Customer"]=df["Customer"].str.strip()
df["Product"]=df["Product"].str.title()
df["Customer"],df["Product"]=df["Customer"].str.strip(),df["Product"].str.title()
df["Product"]=df["Product"].str.lower()
print(df)

    TransactionID Customer     Product  Amount
0            1001     Ravi      Laptop   55000
1            1002    Priya      Mobile   25000
2            1003     Arun      Tablet   30000
3            1004    Sneha  Headphones    5000
4            1005    Kiran       Mouse    1500
5            1006   Anjali    Keyboard    2500
6            1007   Vikram     Monitor   18000
7            1008    Meena      Laptop   55000
8            1009    Rahul      Mobile   22000
9            1010    Sneha  Headphones    5000
10           1010    Sneha  Headphones    5000
11           1011    Kiran       Mouse    1500
    TransactionID Customer     Product  Amount
0            1001     ravi      laptop   55000
1            1002    priya      mobile   25000
2            1003     arun      tablet   30000
3            1004    sneha  headphones    5000
4            1005    kiran       mouse    1500
5            1006   anjali    keyboard    2500
6            1007   vikram     monitor   18000
7            1008    meena      laptop   55000
8            1009    rahul      mobile   22000
9            1010    sneha  headphones    5000
10           1010    sneha  headphones    5000
11           1011    kiran       mouse    1500

In [ ]:
pip install pandas

In [ ]:
import pandas as pd
data = {

   "VisitID": [501, 502, 503, 504, 505,

               506, 507, 508, 509, 510, 510, 511],

   "Patient": ["Rahul", "Anita", "Suresh", "Priya", "Kiran",

               "Anjali", "Ravi", "Meena", "Arun", "Priya",

               "Priya", "Kiran"],

   "Department": ["Cardiology", "Neurology", "Orthopedic", "General",

                  "Dental", "Cardiology", "Neurology", "General",

                  "Dental", "Cardiology", "Cardiology", "Dental"],

   "BillAmount": [5000, 7500, 4500, 2000, 1500,

                  6000, 7000, 2500, 1800, 6000,6000, 1500]}
df_Patient = pd.DataFrame(data)
df.duplicated()
print(df_Patient[df_Patient.duplicated()])
print(df_Patient.duplicated().sum())
print(df_Patient[df_Patient.duplicated(keep=False)])
duplicates = df_Patient[df_Patient.duplicated(keep=False)]
print(duplicates)
df["Department"] = df["Department"].str.title()
print(df)
df["Patient"],df["Department"]=df["Patient"].str.strip().str.title(),df["Department"].str.strip().str.title()

print(df)

    VisitID Patient  Department  BillAmount
10      510   Priya  Cardiology        6000
1
    VisitID Patient  Department  BillAmount
9       510   Priya  Cardiology        6000
10      510   Priya  Cardiology        6000
    VisitID Patient  Department  BillAmount
9       510   Priya  Cardiology        6000
10      510   Priya  Cardiology        6000
    VisitID Patient  Department  BillAmount
0       501   Rahul  Cardiology        5000
1       502   Anita   Neurology        7500
2       503  Suresh  Orthopedic        4500
3       504   Priya     General        2000
4       505   Kiran      Dental        1500
5       506  Anjali  Cardiology        6000
6       507    Ravi   Neurology        7000
7       508   Meena     General        2500
8       509    Arun      Dental        1800
9       510   Priya  Cardiology        6000
10      510   Priya  Cardiology        6000
11      511   Kiran      Dental        1500
    VisitID Patient  Department  BillAmount
0       501   Rahul  Cardiology        5000
1       502   Anita   Neurology        7500
2       503  Suresh  Orthopedic        4500
3       504   Priya     General        2000
4       505   Kiran      Dental        1500
5       506  Anjali  Cardiology        6000
6       507    Ravi   Neurology        7000
7       508   Meena     General        2500
8       509    Arun      Dental        1800
9       510   Priya  Cardiology        6000
10      510   Priya  Cardiology        6000
11      511   Kiran      Dental        1500

In [ ]:
import pandas as pd
data = {
"Date" : ["21-6-25","22-6-25","23-6-25","24-6-25","25-6-25"],
"sales": [5000,6000,3000,2000,7000]}
df = pd.DataFrame(data)
print(df.dtypes)
df["Date"] = pd.to_datetime(df["Date"])
print(df.dtypes)
dates = pd.date_range(
    start = "21-6-25",
    end = "25-6-25"
)
dates = pd.date_range(
    start ="21-6-25",
    periods =365
)
print(dates)
print(df)
dates =pd.date_range(start="21-6-25",periods=10,freq ="D")
print(dates)
print(df)
#me means month end
dates =pd.date_range(start="21-6-25",periods=23,freq ="ME")
print(dates)
print(df)
dates =pd.date_range(start="21-6-25",periods=23,freq ="MS")
print(dates)
print(df)
dates = pd.date_range(start="21-6-25",periods=10,freq="Y")
print(dates)
print(df)
dates = pd.date_range(start="21-6-25",periods=10,freq="MIN")
print(dates)
print(df)
dates = pd.date_range(start="21-6-25",periods=10,freq="S")
print(dates)
print(df)
dates = pd.date_range(
    start = "1-1-25",
    periods = 16

)
print(dates)
dates = pd.date_range(start="1-1-2024",periods=365,freq="D")
print(df)
dates = pd.period_range(start="1-1-2020",periods=60,freq='M')
print(dates)
dates = pd.period_range(start="1-1-2023",periods=24,freq='M')
print(dates)
dates = pd.date_range(start="1-1-24 00:00:00",periods=30*24,freq="H")
print(dates)
dates = pd.period_range(start="1-1-2023",periods=24,freq='M')
print(dates)

Date     object
sales     int64
dtype: object
Date     datetime64[ns]
sales             int64
dtype: object
DatetimeIndex(['2025-06-21', '2025-06-22', '2025-06-23', '2025-06-24',
               '2025-06-25', '2025-06-26', '2025-06-27', '2025-06-28',
               '2025-06-29', '2025-06-30',
               ...
               '2026-06-11', '2026-06-12', '2026-06-13', '2026-06-14',
               '2026-06-15', '2026-06-16', '2026-06-17', '2026-06-18',
               '2026-06-19', '2026-06-20'],
              dtype='datetime64[ns]', length=365, freq='D')
        Date  sales
0 2025-06-21   5000
1 2025-06-22   6000
2 2025-06-23   3000
3 2025-06-24   2000
4 2025-06-25   7000
DatetimeIndex(['2025-06-21', '2025-06-22', '2025-06-23', '2025-06-24',
               '2025-06-25', '2025-06-26', '2025-06-27', '2025-06-28',
               '2025-06-29', '2025-06-30'],
              dtype='datetime64[ns]', freq='D')
        Date  sales
0 2025-06-21   5000
1 2025-06-22   6000
2 2025-06-23   3000
3 2025-06-24   2000
4 2025-06-25   7000
DatetimeIndex(['2025-06-30', '2025-07-31', '2025-08-31', '2025-09-30',
               '2025-10-31', '2025-11-30', '2025-12-31', '2026-01-31',
               '2026-02-28', '2026-03-31', '2026-04-30', '2026-05-31',
               '2026-06-30', '2026-07-31', '2026-08-31', '2026-09-30',
               '2026-10-31', '2026-11-30', '2026-12-31', '2027-01-31',
               '2027-02-28', '2027-03-31', '2027-04-30'],
              dtype='datetime64[ns]', freq='ME')
        Date  sales
0 2025-06-21   5000
1 2025-06-22   6000
2 2025-06-23   3000
3 2025-06-24   2000
4 2025-06-25   7000
DatetimeIndex(['2025-07-01', '2025-08-01', '2025-09-01', '2025-10-01',
               '2025-11-01', '2025-12-01', '2026-01-01', '2026-02-01',
               '2026-03-01', '2026-04-01', '2026-05-01', '2026-06-01',
               '2026-07-01', '2026-08-01', '2026-09-01', '2026-10-01',
               '2026-11-01', '2026-12-01', '2027-01-01', '2027-02-01',
               '2027-03-01', '2027-04-01', '2027-05-01'],
              dtype='datetime64[ns]', freq='MS')
        Date  sales
0 2025-06-21   5000
1 2025-06-22   6000
2 2025-06-23   3000
3 2025-06-24   2000
4 2025-06-25   7000
DatetimeIndex(['2025-12-31', '2026-12-31', '2027-12-31', '2028-12-31',
               '2029-12-31', '2030-12-31', '2031-12-31', '2032-12-31',
               '2033-12-31', '2034-12-31'],
              dtype='datetime64[ns]', freq='YE-DEC')
        Date  sales
0 2025-06-21   5000
1 2025-06-22   6000
2 2025-06-23   3000
3 2025-06-24   2000
4 2025-06-25   7000
DatetimeIndex(['2025-06-21 00:00:00', '2025-06-21 00:01:00',
               '2025-06-21 00:02:00', '2025-06-21 00:03:00',
               '2025-06-21 00:04:00', '2025-06-21 00:05:00',
               '2025-06-21 00:06:00', '2025-06-21 00:07:00',
               '2025-06-21 00:08:00', '2025-06-21 00:09:00'],
              dtype='datetime64[ns]', freq='min')
        Date  sales
0 2025-06-21   5000
1 2025-06-22   6000
2 2025-06-23   3000
3 2025-06-24   2000
4 2025-06-25   7000
DatetimeIndex(['2025-06-21 00:00:00', '2025-06-21 00:00:01',
               '2025-06-21 00:00:02', '2025-06-21 00:00:03',
               '2025-06-21 00:00:04', '2025-06-21 00:00:05',
               '2025-06-21 00:00:06', '2025-06-21 00:00:07',
               '2025-06-21 00:00:08', '2025-06-21 00:00:09'],
              dtype='datetime64[ns]', freq='s')
        Date  sales
0 2025-06-21   5000
1 2025-06-22   6000
2 2025-06-23   3000
3 2025-06-24   2000
4 2025-06-25   7000
DatetimeIndex(['2025-01-01', '2025-01-02', '2025-01-03', '2025-01-04',
               '2025-01-05', '2025-01-06', '2025-01-07', '2025-01-08',
               '2025-01-09', '2025-01-10', '2025-01-11', '2025-01-12',
               '2025-01-13', '2025-01-14', '2025-01-15', '2025-01-16'],
              dtype='datetime64[ns]', freq='D')
        Date  sales
0 2025-06-21   5000
1 2025-06-22   6000
2 2025-06-23   3000
3 2025-06-24   2000
4 2025-06-25   7000
PeriodIndex(['2020-01', '2020-02', '2020-03', '2020-04', '2020-05', '2020-06',
             '2020-07', '2020-08', '2020-09', '2020-10', '2020-11', '2020-12',
             '2021-01', '2021-02', '2021-03', '2021-04', '2021-05', '2021-06',
             '2021-07', '2021-08', '2021-09', '2021-10', '2021-11', '2021-12',
             '2022-01', '2022-02', '2022-03', '2022-04', '2022-05', '2022-06',
             '2022-07', '2022-08', '2022-09', '2022-10', '2022-11', '2022-12',
             '2023-01', '2023-02', '2023-03', '2023-04', '2023-05', '2023-06',
             '2023-07', '2023-08', '2023-09', '2023-10', '2023-11', '2023-12',
             '2024-01', '2024-02', '2024-03', '2024-04', '2024-05', '2024-06',
             '2024-07', '2024-08', '2024-09', '2024-10', '2024-11', '2024-12'],
            dtype='period[M]')
PeriodIndex(['2023-01', '2023-02', '2023-03', '2023-04', '2023-05', '2023-06',
             '2023-07', '2023-08', '2023-09', '2023-10', '2023-11', '2023-12',
             '2024-01', '2024-02', '2024-03', '2024-04', '2024-05', '2024-06',
             '2024-07', '2024-08', '2024-09', '2024-10', '2024-11', '2024-12'],
            dtype='period[M]')
DatetimeIndex(['2024-01-01 00:00:00', '2024-01-01 01:00:00',
               '2024-01-01 02:00:00', '2024-01-01 03:00:00',
               '2024-01-01 04:00:00', '2024-01-01 05:00:00',
               '2024-01-01 06:00:00', '2024-01-01 07:00:00',
               '2024-01-01 08:00:00', '2024-01-01 09:00:00',
               ...
               '2024-01-30 14:00:00', '2024-01-30 15:00:00',
               '2024-01-30 16:00:00', '2024-01-30 17:00:00',
               '2024-01-30 18:00:00', '2024-01-30 19:00:00',
               '2024-01-30 20:00:00', '2024-01-30 21:00:00',
               '2024-01-30 22:00:00', '2024-01-30 23:00:00'],
              dtype='datetime64[ns]', length=720, freq='h')

/tmp/ipykernel_9793/3363801696.py:7: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  df["Date"] = pd.to_datetime(df["Date"])
/tmp/ipykernel_9793/3363801696.py:29: FutureWarning: 'Y' is deprecated and will be removed in a future version, please use 'YE' instead.
  dates = pd.date_range(start="21-6-25",periods=10,freq="Y")
/tmp/ipykernel_9793/3363801696.py:32: FutureWarning: 'MIN' is deprecated and will be removed in a future version, please use 'min' instead.
  dates = pd.date_range(start="21-6-25",periods=10,freq="MIN")
/tmp/ipykernel_9793/3363801696.py:35: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  dates = pd.date_range(start="21-6-25",periods=10,freq="S")
/tmp/ipykernel_9793/3363801696.py:50: FutureWarning: 'H' is deprecated and will be removed in a future version, please use 'h' instead.
  dates = pd.date_range(start="1-1-24 00:00:00",periods=30*24,freq="H")

In [ ]:
import pandas as pd
import numpy as np
dates = pd.date_range(start="2025-01-01",periods=30,freq="D")
sales = np.random.randint(2000,10000,size=30)
df = pd.DataFrame({
    "Date":dates,
    "Sales":sales
})
print(df)
df["Date"]=pd.to_datetime(df["Date"])
df["Date"].dt.year
df[df["Date"].dt.year ==2026]
df.groupby(df["Date"].dt.year)["Sales"].mean()
df.groupby(df["Date"].dt.year)["Sales"].sum()
df.groupby(df["Date"].dt.year)["Sales"].median()
df.groupby(df["Date"].dt.year)["Sales"].min()
df.groupby(df["Date"].dt.year)["Sales"].max()
df.groupby(df["Date"].dt.year)["Sales"].count()
df.groupby(df["Date"].dt.month==5)["Sales"].sum()
df.groupby(df["Date"].dt.month==3)["Sales"].count()
df[df["Date"].dt.month==1]
df["Month"]=df["Date"].dt.month_name()
print(df)
df["Date"].dt.day
df[df["Date"].dt.day==15]
df["Date"].dt.day_name()
print(df)
df[df["Date"].dt.day_name()== "sunday"]
print(df)

         Date  Sales
0  2025-01-01   9900
1  2025-01-02   5001
2  2025-01-03   6889
3  2025-01-04   7087
4  2025-01-05   3038
5  2025-01-06   6661
6  2025-01-07   4467
7  2025-01-08   6472
8  2025-01-09   3862
9  2025-01-10   4862
10 2025-01-11   3507
11 2025-01-12   4104
12 2025-01-13   9735
13 2025-01-14   8522
14 2025-01-15   7072
15 2025-01-16   5323
16 2025-01-17   4153
17 2025-01-18   4428
18 2025-01-19   5809
19 2025-01-20   9920
20 2025-01-21   6240
21 2025-01-22   4673
22 2025-01-23   9665
23 2025-01-24   3171
24 2025-01-25   9845
25 2025-01-26   2698
26 2025-01-27   8986
27 2025-01-28   2858
28 2025-01-29   7782
29 2025-01-30   9672
         Date  Sales    Month
0  2025-01-01   9900  January
1  2025-01-02   5001  January
2  2025-01-03   6889  January
3  2025-01-04   7087  January
4  2025-01-05   3038  January
5  2025-01-06   6661  January
6  2025-01-07   4467  January
7  2025-01-08   6472  January
8  2025-01-09   3862  January
9  2025-01-10   4862  January
10 2025-01-11   3507  January
11 2025-01-12   4104  January
12 2025-01-13   9735  January
13 2025-01-14   8522  January
14 2025-01-15   7072  January
15 2025-01-16   5323  January
16 2025-01-17   4153  January
17 2025-01-18   4428  January
18 2025-01-19   5809  January
19 2025-01-20   9920  January
20 2025-01-21   6240  January
21 2025-01-22   4673  January
22 2025-01-23   9665  January
23 2025-01-24   3171  January
24 2025-01-25   9845  January
25 2025-01-26   2698  January
26 2025-01-27   8986  January
27 2025-01-28   2858  January
28 2025-01-29   7782  January
29 2025-01-30   9672  January
         Date  Sales    Month
0  2025-01-01   9900  January
1  2025-01-02   5001  January
2  2025-01-03   6889  January
3  2025-01-04   7087  January
4  2025-01-05   3038  January
5  2025-01-06   6661  January
6  2025-01-07   4467  January
7  2025-01-08   6472  January
8  2025-01-09   3862  January
9  2025-01-10   4862  January
10 2025-01-11   3507  January
11 2025-01-12   4104  January
12 2025-01-13   9735  January
13 2025-01-14   8522  January
14 2025-01-15   7072  January
15 2025-01-16   5323  January
16 2025-01-17   4153  January
17 2025-01-18   4428  January
18 2025-01-19   5809  January
19 2025-01-20   9920  January
20 2025-01-21   6240  January
21 2025-01-22   4673  January
22 2025-01-23   9665  January
23 2025-01-24   3171  January
24 2025-01-25   9845  January
25 2025-01-26   2698  January
26 2025-01-27   8986  January
27 2025-01-28   2858  January
28 2025-01-29   7782  January
29 2025-01-30   9672  January
         Date  Sales    Month
0  2025-01-01   9900  January
1  2025-01-02   5001  January
2  2025-01-03   6889  January
3  2025-01-04   7087  January
4  2025-01-05   3038  January
5  2025-01-06   6661  January
6  2025-01-07   4467  January
7  2025-01-08   6472  January
8  2025-01-09   3862  January
9  2025-01-10   4862  January
10 2025-01-11   3507  January
11 2025-01-12   4104  January
12 2025-01-13   9735  January
13 2025-01-14   8522  January
14 2025-01-15   7072  January
15 2025-01-16   5323  January
16 2025-01-17   4153  January
17 2025-01-18   4428  January
18 2025-01-19   5809  January
19 2025-01-20   9920  January
20 2025-01-21   6240  January
21 2025-01-22   4673  January
22 2025-01-23   9665  January
23 2025-01-24   3171  January
24 2025-01-25   9845  January
25 2025-01-26   2698  January
26 2025-01-27   8986  January
27 2025-01-28   2858  January
28 2025-01-29   7782  January
29 2025-01-30   9672  January

In [ ]:

import pandas as pd
import numpy as np
dates = pd.period_range(start='2020-01-01', periods=60, freq='M')
sales = np.random.randint(5000, 15000, size=60)
df = pd.DataFrame({
    'Date': dates,
    'Sales': sales
})

print(df)

       Date  Sales
0   2020-01   8256
1   2020-02  13385
2   2020-03   6310
3   2020-04  13987
4   2020-05  10104
5   2020-06  11842
6   2020-07  12403
7   2020-08  13192
8   2020-09   5544
9   2020-10  12824
10  2020-11   9560
11  2020-12  13049
12  2021-01  13735
13  2021-02  12136
14  2021-03   6153
15  2021-04  10615
16  2021-05   9043
17  2021-06   9772
18  2021-07   6370
19  2021-08  10545
20  2021-09   7707
21  2021-10  13383
22  2021-11   6747
23  2021-12  14877
24  2022-01   6478
25  2022-02   6063
26  2022-03  12005
27  2022-04   5323
28  2022-05   6991
29  2022-06  13691
30  2022-07   6579
31  2022-08  14854
32  2022-09   5870
33  2022-10  12208
34  2022-11   8703
35  2022-12   9159
36  2023-01  10507
37  2023-02   8405
38  2023-03  11724
39  2023-04  10205
40  2023-05   8216
41  2023-06  11736
42  2023-07  10088
43  2023-08   8616
44  2023-09   8989
45  2023-10  13193
46  2023-11   7589
47  2023-12  11289
48  2024-01   9825
49  2024-02   7352
50  2024-03  13409
51  2024-04   9887
52  2024-05  10071
53  2024-06   5681
54  2024-07  12440
55  2024-08  14826
56  2024-09  14263
57  2024-10   5717
58  2024-11   6571
59  2024-12  10811

In [ ]:
import pandas as pd
import numpy as np
dates = pd.period_range(start='2024-01-01', periods=365, freq='D')
sales = np.random.randint(5000, 10001, size=365)


df = pd.DataFrame({
    'Date': dates,
    'Sales': sales
})

print(df)

           Date  Sales
0    2024-01-01   8467
1    2024-01-02   9669
2    2024-01-03   8700
3    2024-01-04   5793
4    2024-01-05   8201
..          ...    ...
360  2024-12-26   5345
361  2024-12-27   6800
362  2024-12-28   7787
363  2024-12-29   9956
364  2024-12-30   9972

[365 rows x 2 columns]

In [ ]:
import pandas as pd
import numpy as np
dates = pd.period_range(start='2023-01-01', periods=24, freq='M')
sales = np.random.randint(5000, 15000, size=24)
df = pd.DataFrame({
    'Date': dates,
    'Sales': sales
})

print(df)

       Date  Sales
0   2023-01   5052
1   2023-02   7609
2   2023-03  14002
3   2023-04  11425
4   2023-05   7684
5   2023-06  10666
6   2023-07  14229
7   2023-08   5885
8   2023-09  14984
9   2023-10   6752
10  2023-11   5615
11  2023-12   9545
12  2024-01   8916
13  2024-02  11969
14  2024-03   5684
15  2024-04  12968
16  2024-05   8961
17  2024-06   5437
18  2024-07  13478
19  2024-08   5639
20  2024-09   7720
21  2024-10   8480
22  2024-11  12211
23  2024-12  13770

In [ ]:
import pandas as pd
import numpy as np
dates = pd.period_range(
    start='2024-01-01 00:00:00',
    periods=30 * 24,
    freq='h'
)

sales = np.random.randint(1000, 5000, size=30 * 24)

df = pd.DataFrame({
    'Date': dates,
    'Sales': sales
})

print(df)

                 Date  Sales
0    2024-01-01 00:00   1132
1    2024-01-01 01:00   2084
2    2024-01-01 02:00   3969
3    2024-01-01 03:00   2905
4    2024-01-01 04:00   4338
..                ...    ...
715  2024-01-30 19:00   4156
716  2024-01-30 20:00   4673
717  2024-01-30 21:00   2459
718  2024-01-30 22:00   1834
719  2024-01-30 23:00   1016

[720 rows x 2 columns]

In [ ]:
import pandas as pd
import numpy as np
dates = pd.period_range(start='2020-01-01', periods=60, freq='M')
sales = np.random.randint(5000, 15000, size=60)
df = pd.DataFrame({
    'Date': dates,
    'Sales': sales
})

df['Year'] = df['Date'].dt.year
df['Month'] = df['Date'].dt.month

print("Monthly Sales Data:")
print(df)

yearly_sales = df.groupby('Year')['Sales'].sum()

print("\nTotal Sales for Each Year:")
print(yearly_sales)

Monthly Sales Data:
       Date  Sales  Year  Month
0   2020-01  11247  2020      1
1   2020-02   8453  2020      2
2   2020-03  12871  2020      3
3   2020-04   8244  2020      4
4   2020-05   6561  2020      5
5   2020-06   9327  2020      6
6   2020-07   8484  2020      7
7   2020-08  10161  2020      8
8   2020-09   8618  2020      9
9   2020-10   7030  2020     10
10  2020-11  14550  2020     11
11  2020-12  13601  2020     12
12  2021-01  13832  2021      1
13  2021-02  11151  2021      2
14  2021-03  12649  2021      3
15  2021-04   5329  2021      4
16  2021-05  14088  2021      5
17  2021-06  11021  2021      6
18  2021-07  14932  2021      7
19  2021-08   8070  2021      8
20  2021-09  12863  2021      9
21  2021-10   5533  2021     10
22  2021-11   5129  2021     11
23  2021-12  12202  2021     12
24  2022-01  14550  2022      1
25  2022-02  10915  2022      2
26  2022-03  12434  2022      3
27  2022-04  11613  2022      4
28  2022-05  11173  2022      5
29  2022-06  14733  2022      6
30  2022-07  10959  2022      7
31  2022-08   9907  2022      8
32  2022-09  14730  2022      9
33  2022-10   9899  2022     10
34  2022-11   5626  2022     11
35  2022-12   7205  2022     12
36  2023-01  11425  2023      1
37  2023-02  13893  2023      2
38  2023-03  14395  2023      3
39  2023-04  10588  2023      4
40  2023-05  10307  2023      5
41  2023-06  13446  2023      6
42  2023-07  14003  2023      7
43  2023-08   8251  2023      8
44  2023-09   5722  2023      9
45  2023-10  12980  2023     10
46  2023-11   5633  2023     11
47  2023-12  14786  2023     12
48  2024-01   6043  2024      1
49  2024-02  11328  2024      2
50  2024-03  12761  2024      3
51  2024-04   6991  2024      4
52  2024-05   6606  2024      5
53  2024-06   7079  2024      6
54  2024-07  13440  2024      7
55  2024-08   6988  2024      8
56  2024-09   8873  2024      9
57  2024-10  11598  2024     10
58  2024-11  10705  2024     11
59  2024-12   8091  2024     12

Total Sales for Each Year:
Year
2020    119147
2021    126799
2022    133744
2023    135429
2024    110503
Name: Sales, dtype: int64

In [ ]:
import pandas as pd
import pandas as pd
data = {
    "EmpID": [101,102,103,104,105,106,107,108,109,110,110],
    "Name":["Ravi","PRIYA","Arun", "Sneha","Kiran","ANJALI", "Vikram","meena","RAHUL","Sneha","Sneha"],
    "city":["Hyderabad","Hyderabad","CHENNAI","Chennai","Banglore","BANGLORE","mumbai","mumbai","Delhi","HYDERABAD","HYDERABAD"],
    "salary":[30000,40000,3500,32000,45000,50000,38000,42000,36000,45000,45000]
}
df = pd.DataFrame(data)
df["salary"]=df["salary"].apply(
        lambda x:x*0.10
        )
print(df)
city_codes={
    "Hyderabad":"HYD",
    "Chennai":"CHE",
    "Delhi":"DEL"
  }
df["city_codes"]=df["city"].map(city_codes)
print(df)

    EmpID    Name       city  salary
0     101    Ravi  Hyderabad  3000.0
1     102   PRIYA  Hyderabad  4000.0
2     103    Arun    CHENNAI   350.0
3     104   Sneha    Chennai  3200.0
4     105   Kiran   Banglore  4500.0
5     106  ANJALI   BANGLORE  5000.0
6     107  Vikram     mumbai  3800.0
7     108   meena     mumbai  4200.0
8     109   RAHUL      Delhi  3600.0
9     110   Sneha  HYDERABAD  4500.0
10    110   Sneha  HYDERABAD  4500.0
    EmpID    Name       city  salary city_codes
0     101    Ravi  Hyderabad  3000.0        HYD
1     102   PRIYA  Hyderabad  4000.0        HYD
2     103    Arun    CHENNAI   350.0        NaN
3     104   Sneha    Chennai  3200.0        CHE
4     105   Kiran   Banglore  4500.0        NaN
5     106  ANJALI   BANGLORE  5000.0        NaN
6     107  Vikram     mumbai  3800.0        NaN
7     108   meena     mumbai  4200.0        NaN
8     109   RAHUL      Delhi  3600.0        DEL
9     110   Sneha  HYDERABAD  4500.0        NaN
10    110   Sneha  HYDERABAD  4500.0        NaN

In [ ]:
!pip install numpy
import numpy as np
print(np.__version__)

Requirement already satisfied: numpy in /usr/local/lib/python3.13/dist-packages (2.1.3)
2.1.3

In [ ]:
import numpy as np
numbers = [10,20,30,40,50]
numbers = np.array([10,20,30,40,50])
print(numbers)

[10 20 30 40 50]

In [ ]:
import numpy as np
numbers = [10,20,30,40,50]
arr = np.array([10,20,30,40,50])
print(arr.ndim)

1

In [ ]:
import numpy as np
arr = np.array([
    [10,20,30],
    [40,50,60]
])
print(arr)
print(arr.shape)

[[10 20 30]
 [40 50 60]]
(2, 3)

In [ ]:
import numpy as np
arr = np.array([
    [
    [1,2,3],
    [4,5,6]
],
               [
                   [7,8,9],
                   [10,11,12]
               ]
               ])
print(arr)
print(arr.shape)

(2, 2, 3)

In [ ]:
import numpy as np
arr = np.array([
    [10,20,30],
    [40,50,60]
])
print(arr.shape)

(2, 3)

In [ ]:
import numpy as np
arr = np.array([
    [10,20,30],
    [40,50,60]
])
arr = np.arange(10,30)
print(arr)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29]

In [ ]:
import numpy as np
arr = np.array([
    [10,20,30],
    [40,50,60]
])
arr = np.arange(10,30,2)
print(arr)

[10 12 14 16 18 20 22 24 26 28]

In [ ]:
import numpy as np
numbers = [10,20,30,40,50]
numbers = np.array([10,20,30,40,50])
zeros_1d = np.zeros(5)
print("1D:")
print(zeros_1d)
zeros_2d = np.zeros((2,3))
print("2D:")
print(zeros_2d)
zeros_3d = np.zeros((2,3))
print("3D:")
print(zeros_3d)
ones_1d = np.ones(5)
print("1D:")
print(ones_1d)
ones_2d = np.ones((2,3))
print("2D:")
print(ones_2d)
ones_3d = np.ones((2,3))
print("3D:")
print(ones_3d)
full_1d = np.full(5,10)
print("1D:")
print(full_1d)
full_2d = np.full((2,3),7)
print("2D:")
print(full_2d)
full_3d = np.full((2,2,3),100)
print("3D:")
print(full_3d)

1D:
[0. 0. 0. 0. 0.]
2D:
[[0. 0. 0.]
 [0. 0. 0.]]
3D:
[[0. 0. 0.]
 [0. 0. 0.]]
1D:
[1. 1. 1. 1. 1.]
2D:
[[1. 1. 1.]
 [1. 1. 1.]]
3D:
[[1. 1. 1.]
 [1. 1. 1.]]
1D:
[10 10 10 10 10]
2D:
[[7 7 7]
 [7 7 7]]
3D:
[[[100 100 100]
  [100 100 100]]

 [[100 100 100]
  [100 100 100]]]

In [ ]:
import numpy as np
arr = [10,20,30,40,50,60]
arr= np.array([10,20,30,40,50,60])
a = arr.reshape(2,3)
print(a)
a = arr.reshape(2,3,1)
print(a)

[[10 20 30]
 [40 50 60]]
[[[10]
  [20]
  [30]]

 [[40]
  [50]
  [60]]]

In [ ]:
import numpy as np
arr = [10,20,30,40,50,60,70,80,90,100,56,78,90,90,23,24,56,78,56,70]
arr= np.array([10,20,30,40,50,60,70,80,90,10078,90,90,23,24,56,78,56,70])
arr =np.arange(1,11).reshape(5,2,1)
print(arr)
arr = np.arange(10,50)
print(arr)
arr = np.arange(2,30,2)
print(arr)
arr = np.arange(50,1,-1)
print(arr)
arr = np.arange(1001,1020)
print(arr)
full_1d = np.full(10,7)
print("1D:")
print(full_1d)
full_2d = np.full((2,3),7)
print("2D:")
print(full_2d)

[[[ 1]
  [ 2]]

 [[ 3]
  [ 4]]

 [[ 5]
  [ 6]]

 [[ 7]
  [ 8]]

 [[ 9]
  [10]]]
[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]
[ 2  4  6  8 10 12 14 16 18 20 22 24 26 28]
[50 49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27
 26 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10  9  8  7  6  5  4  3
  2]
[1001 1002 1003 1004 1005 1006 1007 1008 1009 1010 1011 1012 1013 1014
 1015 1016 1017 1018 1019]
1D:
[7 7 7 7 7 7 7 7 7 7]
2D:
[[7 7 7]
 [7 7 7]]

In [ ]:
import numpy as np
roll_numbers = [101,102,103,104,105,106,107,108]
roll_numbers = np.array([101,102,103,104,105,106,107,108])
print(arr.ndim)
print(arr.shape)
zeros_1d = np.zeros(5)
print("1D:")
print(zeros_1d)
zeros_2d = np.zeros(5)
print("2D:")
print(zeros_2d)
ones_1d = np.ones(5)
print("1D:")
print(ones_1d)
ones_2d = np.ones((2,3))
print("2D:")
print(ones_2d)

1
(19,)
1D:
[0. 0. 0. 0. 0.]
2D:
[0. 0. 0. 0. 0.]
1D:
[1. 1. 1. 1. 1.]
2D:
[[1. 1. 1.]
 [1. 1. 1.]]

In [ ]:
import numpy as np
arr =np.array([10.9,20.9,3.0,1],dtype="int")
print(arr)
print(arr.dtype)
arr =np.array([10.9,20.9,3.0,1],dtype="float")
print(arr)
print(arr.dtype)
arr =np.array([10.9,20.9,3.0,1],dtype="str")
print(arr)
print(arr.dtype)
arr = np.array(["vasu","vara","thanu","avi"],dtype="str")
print(arr)
print(arr.dtype)

[10 20  3  1]
int64
[10.9 20.9  3.   1. ]
float64
['10.9' '20.9' '3.0' '1']
<U4
['vasu' 'vara' 'thanu' 'avi']
<U5

In [ ]:
#matrix is always in square
#identity matrix
import numpy as np
arr = np.eye(4)
print(arr)
print("______________________")
#0-1 float numbers
arr = np.random.random(5)
print(arr)
print("______________________")
arr = np.random.random((2,3))
print(arr)
print("______________________")
arr = np.random.random((2,2,3))
print(arr)
print("______________________")
#uniform()--generate ranfom but uniform distribution
#syntax-np.random.uniform(low,high,size)
arr= np.random.uniform(10,50,5)
print(arr)
print("______________________")
#2D array
arr=np.random.uniform(10,50,(2,3))
print(arr)
#3D array
arr=np.random.uniform(10,50,(2,2,3))
print(arr)
#randn() standard normal distribution
arr = np.random.randn(5)
print(arr)
#for mean use arr.mean
print(arr.mean())
#for the standard distribution use arr.std
arr.std
#2D
print("_______________________________________")
arr= np.random.randn(2,3)
print(arr)
#3D
print("_______________________________________")
arr= np.random.randn(2,3,2)
print(arr)
print("__________________________")
#choice -it is used to pick a value from the existed data
arr= np.array([10,20,30,40,50])
result=np.random.choice(arr)
print(result)
#arr,2 or arr,3 for getting 2 or 3 valuess at a time
names=["ravi","priya","arun","sneha"]
result=np.random.choice(names,5)
print(result)
print("____________________________________________________________")
#choice with probability
arr =[10,20,30,40]
result=np.random.choice(arr,size=5,p=[0.5,0.2,0.2,0.1])
print(result)
#seed-we can freeze the data randomly not upto the limit
print("______________________________________________________________")
arr = np.random.uniform(10,50,(2,2,3))
np.random.seed(5)
print(arr)
np.random.seed(10)
print(np.random.random(3))
#shuffle--it will change the existing order
arr = np.array([10, 20, 30, 40, 50])
result = np.random.permutation(arr)
print("Original:")
print(arr)
print("Permutation:")
print(result)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
______________________
[0.61729347 0.55289956 0.74572143 0.86162608 0.72854918]
______________________
[[0.10772842 0.13580843 0.39389722]
 [0.06016401 0.63939714 0.08094428]]
______________________
[[[0.97851505 0.33599925 0.54650935]
  [0.14326867 0.94985784 0.64520537]]

 [[0.7876692  0.35968965 0.54803319]
  [0.60506682 0.82002995 0.5812721 ]]]
______________________
[40.03662205 11.8999252  24.62577182 29.91222244 24.20110005]
______________________
[[13.64086255 38.29499261 39.74693229]
 [10.34315737 14.33012546 40.96766849]]
[[[46.92209049 12.62160503 45.56360764]
  [35.66686944 29.76123161 33.33130893]]

 [[31.8137789  12.95074211 35.81574329]
  [38.86278545 49.88072718 29.66234665]]]
[ 0.95726395  0.53544472 -0.39578568 -1.6107549   1.60340997]
0.21791561408625282
_______________________________________
[[ 0.78224398  0.23406962 -0.16228914]
 [-0.29101947 -0.99766241 -0.20368059]]
_______________________________________
[[[ 0.41789811 -1.50820204]
  [ 0.2683633  -0.41857836]
  [-0.87350765  1.04956951]]

 [[-0.95027715  1.39356557]
  [ 0.37447421  0.2340356 ]
  [ 0.38607855  0.30219702]]]
__________________________
10
['priya' 'ravi' 'sneha' 'ravi' 'arun']
____________________________________________________________
[10 40 10 10 10]
______________________________________________________________
[[[22.68160842 10.04488484 47.36895365]
  [14.0665513  35.64054967 14.78684168]]

 [[15.75028266 43.11804525 12.34545712]
  [18.36531031 12.6182327  25.50702428]]]
[0.77132064 0.02075195 0.63364823]
Original:
[10 20 30 40 50]
Permutation:
[50 30 20 10 40]

In [ ]:
numbers=np.array([10,20,30,40,50])
result = np.random.permutation(numbers)
print("Original:")
print(numbers)
print("Permutation:")
print(result)

Original:
[10 20 30 40 50]
Permutation:
[30 50 40 20 10]

In [ ]:
employees=np.array(["ravi","priya","arun","sneha","kiran"])
np.random.shuffle(employees)
print(employees)

['sneha' 'arun' 'kiran' 'priya' 'ravi']

In [ ]:
marks = np.arange(24)
matrix = marks.reshape(4, 6)
print(matrix)

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]]

In [ ]:
arr = np.zeros(5)
print(arr)
arr = np.zeros((3,4))
print(arr)

[0. 0. 0. 0. 0.]
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]

In [ ]:
arr = np.array([10,20,30,40,50])
print(arr)
arr= np.array([[10,20,30],[40,50,60]])
print(arr)
print(arr.ndim)
arr = np.eye(4,5)
print(arr)

[10 20 30 40 50]
[[10 20 30]
 [40 50 60]]
2
[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]]

In [ ]:
import numpy as np
arr = np.linspace(0,10,5)
print(arr)
arr = np.linspace(0,100,10)
print(arr)
arr = np.linspace(1,50,15)
print(arr)

[ 0.   2.5  5.   7.5 10. ]
[  0.          11.11111111  22.22222222  33.33333333  44.44444444
  55.55555556  66.66666667  77.77777778  88.88888889 100.        ]
[ 1.   4.5  8.  11.5 15.  18.5 22.  25.5 29.  32.5 36.  39.5 43.  46.5
 50. ]

In [ ]:
import numpy as np
arr = np.array([10,20,30,40])
print(arr.shape)

(4,)

In [ ]:
import numpy as np
arr = np.array([
    [1,2,3,4,5],
    [6,7,8,9,10],

])
result = arr.ravel()
print(result)
arr =np.arange(1,11).reshape(2,5,1)
print(arr)
r = arr.T
print(r)
result = arr.transpose()
print(result)
r = arr.ravel()
print(r)
print(arr[1,1])
print(arr[1,4])
print(arr[0:2])
print(arr[0:3,0:3])

[ 1  2  3  4  5  6  7  8  9 10]
[[[ 1]
  [ 2]
  [ 3]
  [ 4]
  [ 5]]

 [[ 6]
  [ 7]
  [ 8]
  [ 9]
  [10]]]
[[[ 1  6]
  [ 2  7]
  [ 3  8]
  [ 4  9]
  [ 5 10]]]
[[[ 1  6]
  [ 2  7]
  [ 3  8]
  [ 4  9]
  [ 5 10]]]
[ 1  2  3  4  5  6  7  8  9 10]
[7]
[10]
[[[ 1]
  [ 2]
  [ 3]
  [ 4]
  [ 5]]

 [[ 6]
  [ 7]
  [ 8]
  [ 9]
  [10]]]
[[[1]
  [2]
  [3]]

 [[6]
  [7]
  [8]]]

In [ ]:
import numpy as np
arr = np.array([10,20,30,40])
new_arr = arr.astype(float)
print(new_arr)
print(new_arr.dtype)
arr[2] = 100
print(arr)
arr[1:3]
print(arr)
n = np.insert(arr,3,89)
print(n)
n = np.insert(arr,2,[95,90])
print(n)
n = np.delete(arr,2)
print(n)
n = np.delete(arr,[2,3])
print(n)

[10. 20. 30. 40.]
float64
[ 10  20 100  40]
[ 10  20 100  40]
[ 10  20 100  89  40]
[ 10  20  95  90 100  40]
[10 20 40]
[10 20]

In [ ]:
import numpy as np
arr = np.array([10,20,30,40,50])
print(arr[0:2])
print(arr[-2:])
print(arr[-3:-1])
print(arr[-1:])

[10 20]
[40 50]
[30 40]
[50]

In [ ]:
import numpy as np
arr = np.array([10,20,30,40,50,60,70])
print(arr[0:1])
print(arr[-1:])
print(arr[3:-3])
print(arr[-2:-1])

[10]
[70]
[40]
[60]

In [ ]:
import numpy as np
arr = np.array([10,20,30,40,50,60,70,80])
for i in range(0,len(arr)-1,2):
  print(arr[i],end= " ")
n = np.delete(arr,[0,1,2,3])
print(n)

10 30 50 70 [50 60 70 80]

In [ ]:
import numpy as np
arr = np.array([10,20,30,40,50])
print(np.sum(arr))

150

In [ ]:
import numpy as np
arr = np.array([10,20,30,40,50,60]).reshape(2,3)
print(np.sum(arr))
print(np.sum(arr))
print(np.mean(arr))
print(np.max(arr))
print(np.sum(arr,axis=0))
print(np.sum(arr,axis=1))
print(np.min(arr))
print(np.min(arr,axis=1))
print(np.mean(arr,axis=1))
print(np.std(arr))
#std indicates standard deviation
print(np.var(arr,axis=0))
print(np.var(arr,axis=1))
print(np.var(arr))
print(np.std(arr,axis=0))
print(np.std(arr,axis=1))
print(np.percentile(arr,100))
np.quantile(arr,0.25)
#percentile--> percentage-->0-100
#quantile--> proportion--> 0-1
print(np.argmax(arr))
#argmax indicates highest position in an array
print(np.argmin(arr))
print(np.argmin(arr,axis=1))
print(np.log10(arr))

210
210
35.0
60
[50 70 90]
[ 60 150]
10
[10 40]
[20. 50.]
17.07825127659933
[225. 225. 225.]
[66.66666667 66.66666667]
291.6666666666667
[15. 15. 15.]
[8.16496581 8.16496581]
60.0
5
0
[0 0]
[[1.         1.30103    1.47712125]
 [1.60205999 1.69897    1.77815125]]

In [ ]:
arr = np.array([10,100,100])
print(np.log10(arr))
print("___________________________")
arr =np.array([10,20,30,40,50,60]).reshape(2,3)
print(np.log10(arr))
print(np.log2(arr))
print(np.log(arr))
print(np.log(2))
print(np.log(3))
print(np.round(arr))

[1. 2. 2.]
___________________________
[[1.         1.30103    1.47712125]
 [1.60205999 1.69897    1.77815125]]
[[3.32192809 4.32192809 4.9068906 ]
 [5.32192809 5.64385619 5.9068906 ]]
[[2.30258509 2.99573227 3.40119738]
 [3.68887945 3.91202301 4.09434456]]
0.6931471805599453
1.0986122886681098
[[10 20 30]
 [40 50 60]]
[[10 20 30]
 [40 50 60]]

In [ ]:
import numpy as np
arr = np.array([50,40,10,30])
result = np.sort(arr)
result = np.sort(arr)[::-1]
print(result)

[50 40 30 10]

In [ ]:
import numpy as np
arr= np.array([10.257,20.678,30.935])
print(np.round(arr))
print(np.round(arr,2))
print(np.floor(arr))
# floor will adjust to the lower limit only
print(np.ceil(arr))
# ceil will display the upper limit only

[10. 21. 31.]
[10.26 20.68 30.94]
[10. 20. 30.]
[11. 21. 31.]

In [ ]:
import numpy as np
arr = np.array([-10,-15,-20,-13])
print(np.abs(arr))
# absolute will print only positive values if we enter negative values also

[10 15 20 13]

In [ ]:
import numpy as np
arr = np.array([10,20,30,40,50])
print(np.sum(arr))
marks = np.array([45,78,92,56,88,67,34])
print(np.max(marks))
print(np.min(marks))
sales = np.array([12000,15000,18000,11000,20000])
print(np.mean(sales))
data = np.array([10,20,30,40,50])
print(np.var(data))
marks = np.array([60,70,80,90,100])
print(np.std(marks))
marks = np.array([35,42,55,60,68,72,80,85,95,100])
print(np.percentile(marks,50))
salary = np.array([25000,30000,35000,40000,45000,50000])
print(np.percentile(marks,75))
print(np.percentile(marks,25))
sales = np.array([15000,22000,18000,35000,27000,12000])
temperatures = np.array([32,28,35,25,30,22,38])
print(np.argmin(temperatures))
arr = np.array([1,2,4,8,16,32])
print(np.log2(arr))
prices = np.array([12.45,23.67,45.89,56.12,78.95])
print(np.round(prices))
arr = np.array([10.2,15.8,20.4,25.9,30.1])
print(np.ceil(arr))
print(np.floor(arr))
profit = np.array([-5000,3000,-2500,4500,-1000])
print(np.abs(profit))
arr = np.array([1,2,3,4,5])
print(np.log(arr))
arr = np.array([4,9,16,25,36,49])
print(np.sqrt(arr))

150
92
34
15200.0
200.0
14.142135623730951
70.0
83.75
56.25
5
[0. 1. 2. 3. 4. 5.]
[12. 24. 46. 56. 79.]
[11. 16. 21. 26. 31.]
[10. 15. 20. 25. 30.]
[5000 3000 2500 4500 1000]
[0.         0.69314718 1.09861229 1.38629436 1.60943791]
[2. 3. 4. 5. 6. 7.]

In [ ]:
import numpy as np
a = np.array(["ravi","anu","kiran","bala","meena"])
print(np.sort(a))
arr = np.array([45,12,89,34,67,23])
print(np.sort(arr))
marks = np.array([78,45,92,66,88,54,99])
print(np.sort(marks))

['anu' 'bala' 'kiran' 'meena' 'ravi']
[12 23 34 45 67 89]
[45 54 66 78 88 92 99]

In [ ]:
import numpy as np
import builtins
print = builtins.print
arr1 = np.array([10,20,30])
arr2 = np.array([40,50,60])
r = np.concatenate((arr1,arr2))
print(r)
# concatenate will merge two dimensions into one

[10 20 30 40 50 60]

In [ ]:
import numpy as np
arr1 = np.array([
    [10,20],
    [30,40]
])
arr2 = np.array([
    [50,60],
    [70,80]])
result = np.concatenate((arr1,arr2),axis=1)
result = np.concatenate((arr1,arr2),axis=0)
print(result)
print(result.ndim)
result = np.vstack((arr1,arr2))
print(result)
print(result.ndim)

[[10 20]
 [30 40]
 [50 60]
 [70 80]]
2
[[10 20]
 [30 40]
 [50 60]
 [70 80]]
2

In [ ]:
import numpy as np
arr1 = np.array([10,20,30])
arr2 = np.array([40,50,60])
result = np.stack((arr1,arr2),axis=0)
print(result)
arr1 = np.array([10,20,30])
arr2 = np.array([40,50,60])
result = np.stack((arr1,arr2),axis=1)
print(result)
print(result.ndim)
arr1 = np.array([10,20,30])
arr2 = np.array([40,50,60])
result = np.vstack((arr1,arr2))
print(result)
print(result.ndim)
arr1 = np.array([10,20,30])
arr2 = np.array([40,50,60])
result = np.hstack((arr1,arr2))
print(result)
print(result.ndim)



# combining a two array by creating a new access

[[10 20 30]
 [40 50 60]]
[[10 40]
 [20 50]
 [30 60]]
2
[[10 20 30]
 [40 50 60]]
2
[10 20 30 40 50 60]
1

In [ ]:
import numpy as np
arr1 = np.array([
    [10,20],
    [30,40],
    [50,60]
])
arr2 = ([
    [30,60],
    [20,10],
    [20,90]
])
arr3 = np.array([
    [60,80],
    [100,90],
    [45,55]
])
result = np.vstack((arr1,arr2,arr3))
print(result)
print(result.ndim)
result = np.hstack((arr1,arr2))
print(result)
print(result.ndim)

[[ 10  20]
 [ 30  40]
 [ 50  60]
 [ 30  60]
 [ 20  10]
 [ 20  90]
 [ 60  80]
 [100  90]
 [ 45  55]]
2
[[10 20 30 60]
 [30 40 20 10]
 [50 60 20 90]]
2

In [ ]:
import numpy as np
arr1 = np.array([10,20,30])
arr2 = np.array([40,50,60])
r=np.concatenate((arr1,arr2))
print(r)
print(np.reshape())

[10 20 30 40 50 60]

In [ ]:
import numpy as np
arr = np.array([10,20,30,40,50,60])
result = np.split(arr,3)
print(result)
np.split(arr,2)

[array([10, 20]), array([30, 40]), array([50, 60])]

[array([10, 20, 30]), array([40, 50, 60])]

In [ ]:
arr = np.array([10,20,30,40,50,60])
result = np.split(arr,[0,3,4])
print(result)

[array([], dtype=int64), array([10, 20, 30]), array([40]), array([50, 60])]

In [ ]:
arr = np.array([
    [10,20,30],
    [30,40,50],
    [50,60,70],
    [70,80,90]
])
result = np.split(arr,2,axis=0)
print(result)
result = np.split(arr,[1,3],axis=1)
print(result)

[array([[10, 20, 30],
       [30, 40, 50]]), array([[50, 60, 70],
       [70, 80, 90]])]
[array([[10],
       [30],
       [50],
       [70]]), array([[20, 30],
       [40, 50],
       [60, 70],
       [80, 90]]), array([], shape=(4, 0), dtype=int64)]